-- AlterEnum
DO $$ BEGIN
  ALTER TYPE "SubjectDeliveryType" ADD VALUE IF NOT EXISTS 'BOTH';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- AlterTable
ALTER TABLE "subjects" ADD COLUMN IF NOT EXISTS "max_marks" INTEGER DEFAULT 100;
ALTER TABLE "subjects" ADD COLUMN IF NOT EXISTS "pass_marks" INTEGER DEFAULT 33;
ALTER TABLE "subjects" ADD COLUMN IF NOT EXISTS "sort_order" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "subjects" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true;
