import { CustomFieldTarget } from "@prisma/client";
import { prisma } from "../../lib/prisma.js";

export type SystemFieldType =
  | "TEXT"
  | "NUMBER"
  | "DATE"
  | "SELECT"
  | "EMAIL"
  | "PHONE"
  | "FILE"
  | "BOOLEAN";

type CatalogField = {
  key: string;
  name: string;
  module: string;
  target: CustomFieldTarget;
  fieldType: SystemFieldType;
  required: boolean;
  unique: boolean;
  description: string;
};

const CATALOG: CatalogField[] = [
  { key: "student_id", name: "Student ID", module: "Students", target: "STUDENT", fieldType: "TEXT", required: true, unique: true, description: "Unique system identifier for each student record." },
  { key: "roll_number", name: "Roll Number", module: "Students", target: "STUDENT", fieldType: "TEXT", required: true, unique: false, description: "Class-wise roll number assigned to the student." },
  { key: "admission_number", name: "Admission Number", module: "Students", target: "STUDENT", fieldType: "TEXT", required: true, unique: true, description: "Official admission number generated by the school." },
  { key: "first_name", name: "First Name", module: "Students", target: "STUDENT", fieldType: "TEXT", required: true, unique: false, description: "Student first / given name." },
  { key: "last_name", name: "Last Name", module: "Students", target: "STUDENT", fieldType: "TEXT", required: false, unique: false, description: "Student surname / family name." },
  { key: "date_of_birth", name: "Date of Birth", module: "Students", target: "STUDENT", fieldType: "DATE", required: true, unique: false, description: "Student date of birth used for age and records." },
  { key: "gender", name: "Gender", module: "Students", target: "STUDENT", fieldType: "SELECT", required: true, unique: false, description: "Student gender selection." },
  { key: "blood_group", name: "Blood Group", module: "Students", target: "STUDENT", fieldType: "SELECT", required: false, unique: false, description: "Medical blood group information." },
  { key: "email", name: "Email", module: "Students", target: "STUDENT", fieldType: "EMAIL", required: false, unique: true, description: "Primary student email address." },
  { key: "phone", name: "Phone", module: "Students", target: "STUDENT", fieldType: "PHONE", required: false, unique: false, description: "Primary student contact number." },
  { key: "address", name: "Address", module: "Students", target: "STUDENT", fieldType: "TEXT", required: false, unique: false, description: "Residential address of the student." },
  { key: "city", name: "City", module: "Students", target: "STUDENT", fieldType: "TEXT", required: false, unique: false, description: "City of residence." },
  { key: "state", name: "State", module: "Students", target: "STUDENT", fieldType: "TEXT", required: false, unique: false, description: "State / province of residence." },
  { key: "pincode", name: "Pincode", module: "Students", target: "STUDENT", fieldType: "TEXT", required: false, unique: false, description: "Postal / ZIP code." },
  { key: "father_name", name: "Father Name", module: "Students", target: "STUDENT", fieldType: "TEXT", required: false, unique: false, description: "Father or primary male guardian name." },
  { key: "mother_name", name: "Mother Name", module: "Students", target: "STUDENT", fieldType: "TEXT", required: false, unique: false, description: "Mother or primary female guardian name." },
  { key: "guardian_phone", name: "Guardian Phone", module: "Students", target: "STUDENT", fieldType: "PHONE", required: true, unique: false, description: "Primary guardian contact number." },
  { key: "class", name: "Class", module: "Students", target: "STUDENT", fieldType: "SELECT", required: true, unique: false, description: "Current academic class of the student." },
  { key: "section", name: "Section", module: "Students", target: "STUDENT", fieldType: "SELECT", required: true, unique: false, description: "Current section within the class." },
  { key: "academic_session", name: "Academic Session", module: "Students", target: "STUDENT", fieldType: "SELECT", required: true, unique: false, description: "Active academic session for enrollment." },
  { key: "photo", name: "Photo", module: "Students", target: "STUDENT", fieldType: "FILE", required: false, unique: false, description: "Student profile photograph." },
  { key: "student_status", name: "Status", module: "Students", target: "STUDENT", fieldType: "SELECT", required: true, unique: false, description: "Enrollment status such as Active or Alumni." },
  { key: "employee_id", name: "Employee ID", module: "Staff", target: "STAFF", fieldType: "TEXT", required: true, unique: true, description: "Unique employee number for staff." },
  { key: "staff_name", name: "Staff Name", module: "Staff", target: "STAFF", fieldType: "TEXT", required: true, unique: false, description: "Full name of the staff member." },
  { key: "designation", name: "Designation", module: "Staff", target: "STAFF", fieldType: "SELECT", required: true, unique: false, description: "Job designation / title." },
  { key: "department", name: "Department", module: "Staff", target: "STAFF", fieldType: "SELECT", required: false, unique: false, description: "Department assignment for the staff." },
  { key: "joining_date", name: "Joining Date", module: "Staff", target: "STAFF", fieldType: "DATE", required: true, unique: false, description: "Date the staff member joined." },
  { key: "basic_salary", name: "Basic Salary", module: "Staff", target: "STAFF", fieldType: "NUMBER", required: false, unique: false, description: "Basic salary amount used in payroll." },
  { key: "bank_account", name: "Bank Account", module: "Staff", target: "STAFF", fieldType: "TEXT", required: false, unique: false, description: "Bank account number for salary credit." },
  { key: "pan_number", name: "PAN Number", module: "Staff", target: "STAFF", fieldType: "TEXT", required: false, unique: true, description: "Permanent Account Number for tax compliance." },
  { key: "aadhaar_number", name: "Aadhaar Number", module: "Staff", target: "STAFF", fieldType: "TEXT", required: false, unique: true, description: "Government identity number." },
  { key: "application_number", name: "Application Number", module: "Admission", target: "ADMISSION", fieldType: "TEXT", required: true, unique: true, description: "Online admission application reference." },
  { key: "applied_class", name: "Applied Class", module: "Admission", target: "ADMISSION", fieldType: "SELECT", required: true, unique: false, description: "Class the applicant is applying for." },
  { key: "previous_school", name: "Previous School", module: "Admission", target: "ADMISSION", fieldType: "TEXT", required: false, unique: false, description: "Name of previous school attended." },
  { key: "fee_invoice_number", name: "Fee Invoice Number", module: "Fees", target: "STUDENT", fieldType: "TEXT", required: true, unique: true, description: "System-generated fee invoice reference." },
  { key: "payment_mode", name: "Payment Mode", module: "Fees", target: "STUDENT", fieldType: "SELECT", required: true, unique: false, description: "Mode of fee payment such as cash or online." },
  { key: "receipt_number", name: "Receipt Number", module: "Fees", target: "STUDENT", fieldType: "TEXT", required: true, unique: true, description: "Receipt number issued after payment." },
  { key: "attendance_date", name: "Attendance Date", module: "Attendance", target: "STUDENT", fieldType: "DATE", required: true, unique: false, description: "Date for which attendance is marked." },
];

export async function getSystemFieldsSetup(tenantId: string) {
  const overrides = await prisma.systemFieldSetting.findMany({
    where: { tenantId },
  });
  const overrideMap = new Map(
    overrides.map((row) => [`${row.target}:${row.fieldKey}`, row]),
  );

  const fields = CATALOG.map((item, index) => {
    const override = overrideMap.get(`${item.target}:${item.key}`);
    const isEnabled = override?.isEnabled ?? true;
    const isRequired = override?.isRequired ?? item.required;
    return {
      id: `${item.target}:${item.key}`,
      index: index + 1,
      key: item.key,
      name: override?.label || item.name,
      module: item.module,
      target: item.target,
      fieldType: item.fieldType,
      required: isRequired,
      unique: item.unique,
      status: isEnabled ? "ACTIVE" : "INACTIVE",
      description: item.description,
      readOnly: true,
      inUse: isEnabled,
    };
  });

  return {
    fields,
    modules: [...new Set(CATALOG.map((item) => item.module))],
    fieldTypes: [...new Set(CATALOG.map((item) => item.fieldType))],
    stats: {
      total: fields.length,
      inUse: fields.filter((item) => item.inUse).length,
      required: fields.filter((item) => item.required).length,
      readOnly: fields.filter((item) => item.readOnly).length,
    },
  };
}
