SET session_replication_role = replica;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx902000lhmmkyb9ilaaq', 'erp.backup', 'Create and restore tenant configuration backups');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zx0004hmmkjux3d0uu', 'hr.view', 'View staff, attendance, leave, ratings, and payroll');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx901000ihmmk5n129xzi', 'homework.evaluate', 'Evaluate homework and request resubmission');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr2ffqj0027hm2016mrned3', 'test_series.manage', 'Create and manage LMS test series from the Question Bank');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsim4eqo0003hmjkvpnrt8qc', 'hostel.manage', 'Manage hostel blocks, rooms, and assignments');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zz000ahmmk58tfct8i', 'documents.generate', 'Generate certificates, ID cards, admit cards, and marksheets');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx96f000ohmmk4zyp7bcj', 'academics.view', 'View academic structure');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9pi000xhmmk84d44ual', 'attendance.manage', 'Mark attendance, review leave, and award points');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsim4eqj0001hmjkr5gposai', 'transport.manage', 'Manage transport routes and assignments');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9j6000uhmmk236gj4v2', 'roles.manage', 'Manage roles and permissions');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjods000fhmt0mmzq82jj', 'rm.manage', 'Full Rich Mount ERP administration');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr6vji10012hmkk27m88b0b', 'live_classes.manage', 'Create and manage LMS live class sessions');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodt000hhmt0huwuqio0', 'rm.quotes.manage', 'Prepare and manage quotations');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodu000ihmt0tvzqfz58', 'rm.quotes.approve', 'Approve and send quotations');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodu000jhmt032hrls9t', 'rm.leads.manage', 'Create and assign leads');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodu000khmt0kfug9iro', 'rm.view', 'View Rich Mount ERP operations');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9ti000zhmmknuczplj9', 'academics.manage', 'Manage academic structure');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zx0002hmmkq6qjhy1s', 'exams.manage', 'Manage exams, students, schedules, and marks');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9le000vhmmkz2u50gtz', 'roles.view', 'View roles and permissions');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodw000qhmt02a3jkhan', 'rm.projects.manage', 'Open and close projects');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zx0003hmmkgihj2pcd', 'exams.publish', 'Publish examination results');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx902000khmmknp736gjh', 'erp.manage', 'Manage ERP configuration');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodw000thmt0rsxa8fyi', 'rm.expenses.approve', 'Approve expenses and post to Zoho');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodw000uhmt0rzo1un5d', 'rm.expenses.manage', 'Record expenses and transfers');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodx000vhmt0ehrlsewm', 'rm.reports.view', 'View and export financial reports');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodx000whmt0eobn4agr', 'rm.zoho.manage', 'Manage Zoho Books integration');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodx000xhmt0fmg8s4ui', 'rm.ocr.manage', 'Upload and confirm OCR receipts');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr1pdzv0010hms8ccg7vl2a', 'question_bank.manage', 'Manage question bank questions, types, and settings');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zy0005hmmkw3ozeodl', 'hr.manage', 'Manage staff, attendance, leave, and ratings');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9nh000whmmksua5qajj', 'attendance.view', 'View student attendance and reports');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9xf0011hmmkjnfd5aln', 'sessions.manage', 'Manage academic sessions');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr2ffqh0026hm207b4e8g0n', 'test_series.view', 'View LMS test series and papers');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsim4eqm0002hmjk8ty5mfzh', 'hostel.view', 'View hostel blocks, rooms, and assignments');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9rg000yhmmk1s0bj88h', 'users.manage', 'Manage tenant users');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx901000fhmmkr30wzjfy', 'homework.manage', 'Create and manage homework assignments');
SET session_replication_role = DEFAULT;