SET session_replication_role = replica;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9h2000thmmk1runs8b8', 'fees.manage', 'Manage fee setup and assignments');
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tax000jhmzk439r8x0i', 'library.view', 'View library books and loans');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9co000rhmmk54n8bozo', 'students.manage', 'Manage students and enrolments');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx925000mhmmkvdtwtt8a', 'settings.manage', 'Manage tenant settings');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx902000jhmmkvgauqoji', 'erp.view', 'View ERP configuration');
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb2000mhmzkzpwj8me7', 'inventory.manage', 'Manage inventory stock and issue items');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsrd461n0013hm58pl72pbq0', 'ncert.manage', 'Create and manage LMS NCERT study resources');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx946000nhmmkxuw7qsm9', 'platform.manage', 'Manage the SaaS CMS LMS platform');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr5kg8v0010hm9ody2lr6yh', 'lesson_planning.view', 'View LMS lesson plans');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsrd461l0011hm58h7k94dpm', 'ncert.view', 'View LMS NCERT study resources');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx900000dhmmkfn2tioxy', 'homework.view', 'View homework, submissions, and reports');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx901000hhmmkk536cn6p', 'homework.submit', 'Submit and resubmit homework');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsrfswge000ghmrsftlucb1x', 'academic_calendar.view', 'View LMS academic calendar events');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zz0009hmmk61uvtfdi', 'payroll.manage', 'Generate and pay staff payroll');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx900000bhmmkq4dm6u1o', 'reports.view', 'View consolidated module reports and audit trail');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr5kg900013hm9o01u3w9xr', 'lesson_planning.manage', 'Create and manage LMS lesson plans');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx9al000qhmmk8l9j0zzj', 'fees.view', 'View fees, dues, receipts, and reports');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx98m000phmmkc97o4j68', 'settings.view', 'View tenant settings');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zz0007hmmklbvn9yy3', 'documents.view', 'View templates and generated documents');
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb3000nhmzkw5eautgl', 'online_exam.view', 'View online exams, attempts, and ranks');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx900000chmmkvama9xz0', 'timetable.manage', 'Create and manage timetable periods');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zz0008hmmk8m7vd2ut', 'students.view', 'View students and enrolments');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx900000ehmmky7ydk11m', 'timetable.view', 'View class and teacher timetables');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx901000ghmmk2v5ga1w6', 'sessions.view', 'View academic sessions');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zk0000hmmkteq0gjsz', 'tenants.manage', 'Create and administer tenants');
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zy0006hmmk2aer223s', 'documents.manage', 'Design certificate, ID card, and exam templates');
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodu000lhmt0jb793itk', 'notifications.manage', 'Send campus notifications and announcements');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr6vjhu000whmkkqj85j3b3', 'live_classes.view', 'View LMS live class sessions');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsrfswge000hhmrslus4v06f', 'academic_calendar.manage', 'Create and manage LMS academic calendar events');
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb1000khmzkxf5g2h6t', 'library.manage', 'Manage library books and issue/return');
INSERT INTO public.permissions (id, key, description) VALUES ('cmsim4eq50000hmjkjhevijq1', 'transport.view', 'View transport routes and assignments');
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb4000ohmzktb3alda3', 'online_exam.manage', 'Manage online exams, questions, attempts, and grading');
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0002hm4cf2rs69da', 'cmrvmxa4u0014hmmkreax8o99', 'all_students', 'All Students', 'Broadcast to every student device', 0, true, 1, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096');
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0003hm4cgz1uhqnb', 'cmrvmxa4u0014hmmkreax8o99', 'all_parents', 'All Parents', 'Broadcast to every parent/guardian device', 0, true, 2, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096');
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0004hm4c7ef10qwv', 'cmrvmxa4u0014hmmkreax8o99', 'teachers', 'Teachers', 'Staff and teacher devices', 0, true, 3, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096');
SET session_replication_role = DEFAULT;