SET session_replication_role = replica;
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0012hm1ouiby5u3n', 'cmrvmxa4u0014hmmkreax8o99', 'late_arrival', 'Late Arrival', 'Notify late check-in', 'ATTENDANCE', 'late_arrival', 'On Late Arrival', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Late Arrival', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0013hm1ougtgs8ky', 'cmrvmxa4u0014hmmkreax8o99', 'attendance_summary', 'Weekly Attendance Summary', 'Weekly attendance digest', 'ATTENDANCE', 'attendance_weekly', 'Every Monday 8 AM', 'MEDIUM', 'SCHEDULED', true, true, true, false, true, true, false, 'Weekly Attendance Summary', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0014hm1oeje122mu', 'cmrvmxa4u0014hmmkreax8o99', 'low_attendance_warning', 'Low Attendance Warning', 'Alert when attendance drops', 'ATTENDANCE', 'low_attendance', 'Below 75% Threshold', 'HIGH', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Low Attendance Warning', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0015hm1od4007yz5', 'cmrvmxa4u0014hmmkreax8o99', 'staff_absent', 'Staff Absent Alert', 'Notify HR of staff absence', 'ATTENDANCE', 'staff_absent', 'On Staff Absent', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Staff Absent Alert', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0016hm1owiyl5gaf', 'cmrvmxa4u0014hmmkreax8o99', 'leave_approved', 'Leave Approved', 'Staff leave approval notice', 'HR', 'leave_approved', 'On Leave Approved', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Leave Approved', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0017hm1ouyrdhrih', 'cmrvmxa4u0014hmmkreax8o99', 'leave_rejected', 'Leave Rejected', 'Staff leave rejection notice', 'HR', 'leave_rejected', 'On Leave Rejected', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Leave Rejected', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0018hm1oj70k9q5i', 'cmrvmxa4u0014hmmkreax8o99', 'payroll_processed', 'Payroll Processed', 'Salary processed confirmation', 'HR', 'payroll_processed', 'On Payroll Processed', 'HIGH', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Payroll Processed', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0019hm1o0xqt6fuy', 'cmrvmxa4u0014hmmkreax8o99', 'staff_announcement', 'Staff Announcement', 'Broadcast HR announcements', 'HR', 'staff_announcement', 'On Announcement Publish', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Staff Announcement', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001ahm1o5z5pjz7t', 'cmrvmxa4u0014hmmkreax8o99', 'appraisal_reminder', 'Appraisal Reminder', 'Upcoming appraisal cycle', 'HR', 'appraisal_reminder', '7 Days Before Cycle', 'MEDIUM', 'SCHEDULED', true, true, true, false, false, false, true, 'Appraisal Reminder', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001bhm1ob8js9nat', 'cmrvmxa4u0014hmmkreax8o99', 'school_announcement', 'School Announcement', 'General campus announcements', 'GENERAL', 'announcement', 'On Announcement Publish', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, true, 'School Announcement', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001chm1o00bmir8x', 'cmrvmxa4u0014hmmkreax8o99', 'holiday_notice', 'Holiday Notice', 'Notify declared holidays', 'GENERAL', 'holiday_declared', 'On Holiday Declared', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, true, 'Holiday Notice', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001dhm1ow4izxzh8', 'cmrvmxa4u0014hmmkreax8o99', 'emergency_alert', 'Emergency Alert', 'Critical campus emergency', 'GENERAL', 'emergency', 'On Emergency Raised', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, true, 'Emergency Alert', 'Hello {{name}},
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ehm1owql5q8gk', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001fhm1oxbu5m0bq', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ghm1oqd0d5jce', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001hhm1odecm8t8v', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ihm1oa651egkv', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001jhm1oct9vofz0', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001khm1oqgak05k0', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001lhm1o56m4u18i', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001mhm1oedhto8x9', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'sms', 13, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001nhm1oxdvos4nm', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ohm1o8utus46d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001phm1owc5h7qsd', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001qhm1o6b8ancg8', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001rhm1ow2tqlfmz', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001shm1orzyzn53d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001thm1o4ff5j567', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001uhm1oav9dy94b', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001vhm1oruc19r4d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001whm1okhxd8dkw', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001xhm1ohtdgwtny', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001yhm1oq0t0oype', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001zhm1odlfp4zzx', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00');
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0020hm1o4zclcwtl', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00');
SET session_replication_role = DEFAULT;