SET session_replication_role = replica;
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0015hm1od4007yz5', 'cmrvmxa4u0014hmmkreax8o99', 'staff_absent', 'Staff Absent Alert', 'Notify HR of staff absence', 'ATTENDANCE', 'staff_absent', 'On Staff Absent', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Staff Absent Alert', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0016hm1owiyl5gaf', 'cmrvmxa4u0014hmmkreax8o99', 'leave_approved', 'Leave Approved', 'Staff leave approval notice', 'HR', 'leave_approved', 'On Leave Approved', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Leave Approved', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0017hm1ouyrdhrih', 'cmrvmxa4u0014hmmkreax8o99', 'leave_rejected', 'Leave Rejected', 'Staff leave rejection notice', 'HR', 'leave_rejected', 'On Leave Rejected', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Leave Rejected', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0018hm1oj70k9q5i', 'cmrvmxa4u0014hmmkreax8o99', 'payroll_processed', 'Payroll Processed', 'Salary processed confirmation', 'HR', 'payroll_processed', 'On Payroll Processed', 'HIGH', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Payroll Processed', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0019hm1o0xqt6fuy', 'cmrvmxa4u0014hmmkreax8o99', 'staff_announcement', 'Staff Announcement', 'Broadcast HR announcements', 'HR', 'staff_announcement', 'On Announcement Publish', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Staff Announcement', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001ahm1o5z5pjz7t', 'cmrvmxa4u0014hmmkreax8o99', 'appraisal_reminder', 'Appraisal Reminder', 'Upcoming appraisal cycle', 'HR', 'appraisal_reminder', '7 Days Before Cycle', 'MEDIUM', 'SCHEDULED', true, true, true, false, false, false, true, 'Appraisal Reminder', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001bhm1ob8js9nat', 'cmrvmxa4u0014hmmkreax8o99', 'school_announcement', 'School Announcement', 'General campus announcements', 'GENERAL', 'announcement', 'On Announcement Publish', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, true, 'School Announcement', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001chm1o00bmir8x', 'cmrvmxa4u0014hmmkreax8o99', 'holiday_notice', 'Holiday Notice', 'Notify declared holidays', 'GENERAL', 'holiday_declared', 'On Holiday Declared', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, true, 'Holiday Notice', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001dhm1ow4izxzh8', 'cmrvmxa4u0014hmmkreax8o99', 'emergency_alert', 'Emergency Alert', 'Critical campus emergency', 'GENERAL', 'emergency', 'On Emergency Raised', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, true, 'Emergency Alert', 'Hello {{name}},
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ehm1owql5q8gk', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001fhm1oxbu5m0bq', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ghm1oqd0d5jce', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001hhm1odecm8t8v', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ihm1oa651egkv', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001jhm1oct9vofz0', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001khm1oqgak05k0', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001lhm1o56m4u18i', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001mhm1oedhto8x9', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'sms', 13, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001nhm1oxdvos4nm', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ohm1o8utus46d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001phm1owc5h7qsd', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001qhm1o6b8ancg8', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001rhm1ow2tqlfmz', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001shm1orzyzn53d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001thm1o4ff5j567', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001uhm1oav9dy94b', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001vhm1oruc19r4d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001whm1okhxd8dkw', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001xhm1ohtdgwtny', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001yhm1oq0t0oype', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001zhm1odlfp4zzx', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0020hm1o4zclcwtl', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0021hm1o5mnfiukn', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0022hm1o4566rbi2', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'sms', 13, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0023hm1o9f7hdjrm', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0024hm1o2bhh5u8i', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0025hm1oi9fp9pxm', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0026hm1o4ebwmito', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0027hm1onv9u2kif', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0028hm1oz42awkid', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0029hm1opdpkq31v', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ahm1o0hqq7gdb', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002bhm1ofn8tnj28', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002chm1offt4y85g', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002dhm1osyji8w2h', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ehm1o8fvamkhd', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002fhm1o5ov4866u', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ghm1omalkhmmf', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002hhm1o2vqb0zlg', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ihm1oj5nnlhu7', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002jhm1oa632nkzy', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002khm1o2fpjn7sa', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002lhm1o6nrb5mig', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002mhm1o5swrl5ox', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002nhm1orxwf25tf', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx901000ghmmk2v5ga1w6', 'sessions.view', 'View academic sessions') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zk0000hmmkteq0gjsz', 'tenants.manage', 'Create and administer tenants') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zy0006hmmk2aer223s', 'documents.manage', 'Design certificate, ID card, and exam templates') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodu000lhmt0jb793itk', 'notifications.manage', 'Send campus notifications and announcements') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr6vjhu000whmkkqj85j3b3', 'live_classes.view', 'View LMS live class sessions') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmsrfswge000hhmrslus4v06f', 'academic_calendar.manage', 'Create and manage LMS academic calendar events') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb1000khmzkxf5g2h6t', 'library.manage', 'Manage library books and issue/return') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmsim4eq50000hmjkjhevijq1', 'transport.view', 'View transport routes and assignments') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb4000ohmzktb3alda3', 'online_exam.manage', 'Manage online exams, questions, attempts, and grading') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0002hm4cf2rs69da', 'cmrvmxa4u0014hmmkreax8o99', 'all_students', 'All Students', 'Broadcast to every student device', 0, true, 1, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0003hm4cgz1uhqnb', 'cmrvmxa4u0014hmmkreax8o99', 'all_parents', 'All Parents', 'Broadcast to every parent/guardian device', 0, true, 2, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0004hm4c7ef10qwv', 'cmrvmxa4u0014hmmkreax8o99', 'teachers', 'Teachers', 'Staff and teacher devices', 0, true, 3, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0005hm4cxvqir8vr', 'cmrvmxa4u0014hmmkreax8o99', 'examination', 'Examination', 'Exam schedules and result alerts', 0, true, 4, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0006hm4c8r4lxcrz', 'cmrvmxa4u0014hmmkreax8o99', 'fee_reminder', 'Fee Reminder', 'Fee due and payment confirmations', 0, true, 5, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.tenant_question_bank_settings (id, tenant_id, scope, enabled_question_types, show_question_marks, enabled_difficulties, auto_question_code, default_marks, negative_marking_enabled, negative_marks, negative_apply_to, prevent_duplicates, shuffle_questions, shuffle_options, allow_import, allow_export, require_approval, created_at, updated_at) VALUES ('cmskb868e0001hmo8cmhfu3og', 'cmrvmxa4u0014hmmkreax8o99', 'GLOBAL', '{MCQ_SINGLE,MCQ_MULTI,TRUE_FALSE,SHORT_ANSWER,LONG_ANSWER,FILL_BLANKS}', true, '{EASY,MEDIUM,HARD}', true, '{"MATCHING": 1, "MCQ_MULTI": 1, "MCQ_SINGLE": 1, "TRUE_FALSE": 1, "FILL_BLANKS": 1, "LONG_ANSWER": 5, "SHORT_ANSWER": 2}', true, 0.25, 'ALL', true, true, true, true, true, false, '2026-08-08 11:48:16.142', '2026-08-08 11:48:16.142') ON CONFLICT DO NOTHING;
INSERT INTO public.tenant_question_bank_settings (id, tenant_id, scope, enabled_question_types, show_question_marks, enabled_difficulties, auto_question_code, default_marks, negative_marking_enabled, negative_marks, negative_apply_to, prevent_duplicates, shuffle_questions, shuffle_options, allow_import, allow_export, require_approval, created_at, updated_at) VALUES ('cmsr1za85001hhmew36lb4vw3', 'cmspvcx300018hmzk7qyhss52', 'GLOBAL', '{MCQ_SINGLE,MCQ_MULTI,TRUE_FALSE,SHORT_ANSWER,LONG_ANSWER,FILL_BLANKS}', true, '{EASY,MEDIUM,HARD}', true, '{"MATCHING": 1, "MCQ_MULTI": 1, "MCQ_SINGLE": 1, "TRUE_FALSE": 1, "FILL_BLANKS": 1, "LONG_ANSWER": 5, "SHORT_ANSWER": 2}', true, 0.25, 'ALL', true, true, true, true, true, false, '2026-08-13 05:03:48.101', '2026-08-13 05:03:48.101') ON CONFLICT DO NOTHING;
INSERT INTO public.question_bank_difficulty_rules (id, tenant_id, setting_id, level, from_percent, to_percent, description, sort_order, created_at, updated_at) VALUES ('cmskb868e0002hmo8avuo1oog', 'cmrvmxa4u0014hmmkreax8o99', 'cmskb868e0001hmo8cmhfu3og', 'EASY', 71, 100, 'Most students answer correctly', 1, '2026-08-08 11:48:16.142', '2026-08-08 11:48:16.142') ON CONFLICT DO NOTHING;
SET session_replication_role = DEFAULT;
SET session_replication_role = DEFAULT;