SET session_replication_role = replica;
SET session_replication_role = replica;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0027hm943asdtv97', 'cmspvcx300018hmzk7qyhss52', 'syllabus_update_msg', 'Syllabus Update', 'Syllabus change alert', 'MESSAGE', 'Academics', 'en', NULL, 'Syllabus for {{Class}}-{{Section}} has been updated. Please review on the app.', true, false, true, false, true, true, 28, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0028hm94ml3rfqod', 'cmspvcx300018hmzk7qyhss52', 'event_invite_msg', 'Event Invitation', 'School event invite', 'MESSAGE', 'General', 'en', NULL, 'You are invited to {{School Name}} event on {{Date}} at {{Time}}. — {{School Name}}', true, true, true, false, true, true, 29, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0029hm94b0g1tgrz', 'cmspvcx300018hmzk7qyhss52', 'birthday_wish_msg', 'Birthday Wish', 'Student birthday greeting', 'MESSAGE', 'General', 'en', NULL, 'Happy Birthday {{Student Name}}! Wishing you a wonderful year ahead. — {{School Name}}', true, false, true, false, true, true, 30, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002ahm949hmucv38', 'cmspvcx300018hmzk7qyhss52', 'staff_leave_approved', 'Staff Leave Approved', 'Leave approval for staff', 'MESSAGE', 'HR', 'en', NULL, 'Dear {{Staff Name}}, your leave on {{Date}} has been approved. — {{School Name}}', true, false, true, false, true, true, 31, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002bhm94ivhcm3ce', 'cmspvcx300018hmzk7qyhss52', 'payroll_processed_msg', 'Payroll Processed', 'Salary processed alert', 'MESSAGE', 'HR', 'en', NULL, 'Dear {{Staff Name}}, payroll for this month has been processed. — {{School Name}}', true, false, true, true, true, true, 32, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002chm94lwgzjd23', 'cmspvcx300018hmzk7qyhss52', 'emergency_alert_msg', 'Emergency Alert', 'Critical emergency broadcast', 'MESSAGE', 'General', 'en', NULL, 'EMERGENCY from {{School Name}}: please check your phone / portal immediately.', true, true, true, false, true, true, 33, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002dhm94sxi4kcm8', 'cmspvcx300018hmzk7qyhss52', 'revaluation_update_msg', 'Revaluation Update', 'Revaluation status message', 'MESSAGE', 'Examinations', 'en', NULL, 'Revaluation update for {{Student Name}} ({{Exam Name}}) is available on the portal.', true, false, true, false, false, true, 34, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002ehm94g1oj6upk', 'cmspvcx300018hmzk7qyhss52', 'waitlist_update_msg', 'Waitlist Update', 'Admission waitlist change', 'MESSAGE', 'Admission', 'en', NULL, 'Waitlist status for {{Student Name}} has been updated. Please check the portal.', true, true, true, false, false, false, 35, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002fhm94kagcd77d', 'cmspvcx300018hmzk7qyhss52', 'unused_promo_msg', 'Promotional Offer', 'Unused promotional template', 'MESSAGE', 'General', 'en', NULL, 'Special offer from {{School Name}} for {{Parent Name}}. Contact office for details.', true, true, true, false, false, false, 36, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002ghm949ak7vswv', 'cmspvcx300018hmzk7qyhss52', 'exam_timetable_notice', 'Exam Timetable Notice', 'Published exam timetable for portal', 'NOTICE', 'Examinations', 'en', 'Exam Timetable Notice', 'Dear Parents,
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002hhm94mk9q8yab', 'cmspvcx300018hmzk7qyhss52', 'fee_structure_notice', 'Fee Structure Notice', 'Annual fee structure announcement', 'NOTICE', 'Fees', 'en', 'Fee Structure Notice', 'Fee structure for the academic year is now available. Please review dues for {{Student Name}} ({{Class}}-{{Section}}).', false, false, true, true, true, true, 38, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002ihm94luduwtsk', 'cmspvcx300018hmzk7qyhss52', 'academic_calendar_notice', 'Academic Calendar Notice', 'Calendar publication notice', 'NOTICE', 'Academics', 'en', 'Academic Calendar Notice', 'Academic calendar has been updated. Holidays and events are listed on the portal.', false, false, true, true, true, true, 39, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002jhm946cgaqy8c', 'cmspvcx300018hmzk7qyhss52', 'uniform_policy_notice', 'Uniform Policy Notice', 'Dress code reminder', 'NOTICE', 'General', 'en', 'Uniform Policy Notice', 'All students must follow the school uniform policy from {{Date}}. Contact office for queries.', false, false, true, true, true, true, 40, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002khm94g4lx6hci', 'cmspvcx300018hmzk7qyhss52', 'ptm_notice', 'Parent Teacher Meeting', 'PTM schedule notice', 'NOTICE', 'General', 'en', 'Parent Teacher Meeting', 'PTM for {{Class}}-{{Section}} will be held on {{Date}} at {{Time}}. Your presence is requested.', false, false, true, true, true, true, 41, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002lhm94zlocwtdo', 'cmspvcx300018hmzk7qyhss52', 'result_declaration_notice', 'Result Declaration', 'Result day notice', 'NOTICE', 'Examinations', 'en', 'Result Declaration', 'Results for {{Exam Name}} will be declared on {{Date}}. Parents may collect report cards from school.', false, false, true, true, true, true, 42, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002mhm9462d5wimf', 'cmspvcx300018hmzk7qyhss52', 'sports_day_notice', 'Sports Day Notice', 'Annual sports day invite', 'NOTICE', 'General', 'en', 'Sports Day Notice', 'Annual Sports Day will be celebrated on {{Date}}. Students of {{Class}} are requested to participate.', false, false, true, true, true, true, 43, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002nhm94s3kwchm9', 'cmspvcx300018hmzk7qyhss52', 'library_rules_notice', 'Library Rules', 'Library usage guidelines', 'NOTICE', 'Library', 'en', 'Library Rules', 'Updated library rules are in effect from {{Date}}. Please ensure books are returned by {{Due Date}}.', false, false, true, true, true, true, 44, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002ohm94rz39163r', 'cmspvcx300018hmzk7qyhss52', 'transport_route_notice', 'Transport Route Change', 'Bus route update notice', 'NOTICE', 'Transport', 'en', 'Transport Route Change', 'Transport routes have been revised. Please check the updated stop timings on the portal.', false, false, true, true, true, true, 45, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002phm94k82nvqjv', 'cmspvcx300018hmzk7qyhss52', 'health_checkup_notice', 'Health Checkup Notice', 'Annual health checkup', 'NOTICE', 'General', 'en', 'Health Checkup Notice', 'Health checkup for students will be conducted on {{Date}}. Consent forms are available on the portal.', false, false, true, true, true, true, 46, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002qhm94aknrqulc', 'cmspvcx300018hmzk7qyhss52', 'exam_hall_ticket_notice', 'Hall Ticket Notice', 'Hall ticket collection', 'NOTICE', 'Examinations', 'en', 'Hall Ticket Notice', 'Hall tickets for {{Exam Name}} are ready. Collect from office with Adm No {{Adm No}}.', false, false, true, true, true, true, 47, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002rhm94xa0vg65n', 'cmspvcx300018hmzk7qyhss52', 'attendance_policy_notice', 'Attendance Policy', 'Minimum attendance policy', 'NOTICE', 'Attendance', 'en', 'Attendance Policy', 'Students must maintain minimum attendance. Parents of {{Student Name}} will be notified if below threshold.', false, false, true, true, true, true, 48, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002shm94x5nlrei1', 'cmspvcx300018hmzk7qyhss52', 'unused_draft_notice', 'Draft Circular', 'Unused draft circular', 'NOTICE', 'General', 'en', 'Draft Circular', 'Draft circular content for internal review only.', false, false, true, true, false, false, 49, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002thm944wnopcl2', 'cmspvcx300018hmzk7qyhss52', 'summer_camp_notice', 'Summer Camp Notice', 'Summer camp registration', 'NOTICE', 'General', 'en', 'Summer Camp Notice', 'Summer camp registration opens on {{Date}}. Limited seats for {{Class}} students.', false, false, true, true, true, true, 50, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002uhm94d0y5zm5q', 'cmspvcx300018hmzk7qyhss52', 'welcome_email', 'Welcome Email', 'Full welcome email for new admissions', 'EMAIL', 'Admission', 'en', 'Welcome Email', 'Dear {{Parent Name}},
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002vhm94am4pm6fh', 'cmspvcx300018hmzk7qyhss52', 'fee_invoice_email', 'Fee Invoice Email', 'Detailed fee invoice email', 'EMAIL', 'Fees', 'en', 'Fee Invoice Email', 'Dear {{Parent Name}},
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002whm94nkhkawb1', 'cmspvcx300018hmzk7qyhss52', 'report_card_email', 'Report Card Email', 'Report card delivery email', 'EMAIL', 'Examinations', 'en', 'Report Card Email', 'Dear {{Parent Name}},
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002xhm94duvmwp02', 'cmspvcx300018hmzk7qyhss52', 'leave_status_email', 'Leave Status Email', 'Staff leave status email', 'EMAIL', 'HR', 'en', 'Leave Status Email', 'Dear {{Staff Name}},
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002yhm94roz9i0tt', 'cmspvcx300018hmzk7qyhss52', 'newsletter_email', 'Monthly Newsletter', 'School newsletter email', 'EMAIL', 'General', 'en', 'Monthly Newsletter', 'Dear Parents,
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002zhm94yow93lxu', 'cmspvcx300018hmzk7qyhss52', 'password_reset_email', 'Password Reset', 'Portal password reset email', 'EMAIL', 'System', 'en', 'Password Reset', 'Dear user,
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk0030hm94pv771rmo', 'cmspvcx300018hmzk7qyhss52', 'event_confirmation_email', 'Event Confirmation', 'Event registration confirmation', 'EMAIL', 'General', 'en', 'Event Confirmation', 'Dear {{Parent Name}},
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk0031hm94ljomoqoj', 'cmspvcx300018hmzk7qyhss52', 'unused_alumni_email', 'Alumni Outreach', 'Unused alumni outreach email', 'EMAIL', 'General', 'en', 'Alumni Outreach', 'Dear Alumni,
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0002hm1o2rrj5bsi', 'cmrvmxa4u0014hmmkreax8o99', 'admission_confirmation', 'Admission Confirmation', 'Notify when admission is approved', 'ADMISSION', 'admission_approved', 'On Admission Approved', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, false, 'Admission Confirmation', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0003hm1osoe9qs0m', 'cmrvmxa4u0014hmmkreax8o99', 'admission_rejected', 'Admission Rejected', 'Notify when application is rejected', 'ADMISSION', 'admission_rejected', 'On Admission Rejected', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, true, false, 'Admission Rejected', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0004hm1obmo31zra', 'cmrvmxa4u0014hmmkreax8o99', 'admission_document_request', 'Document Request', 'Ask for pending admission documents', 'ADMISSION', 'docs_requested', 'On Documents Requested', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Document Request', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0005hm1owit8qzd5', 'cmrvmxa4u0014hmmkreax8o99', 'admission_fee_pending', 'Admission Fee Pending', 'Remind unpaid admission fee', 'ADMISSION', 'admission_fee_due', 'On Fee Pending', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, false, 'Admission Fee Pending', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0006hm1o8pkdu083', 'cmrvmxa4u0014hmmkreax8o99', 'admission_interview', 'Interview Scheduled', 'Share interview slot details', 'ADMISSION', 'interview_scheduled', 'On Interview Scheduled', 'MEDIUM', 'SCHEDULED', true, true, true, false, true, true, false, 'Interview Scheduled', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0007hm1oiriq3x54', 'cmrvmxa4u0014hmmkreax8o99', 'admission_waitlist', 'Waitlist Update', 'Update waitlisted applicants', 'ADMISSION', 'waitlist_updated', 'On Waitlist Change', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Waitlist Update', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0008hm1ogo12094l', 'cmrvmxa4u0014hmmkreax8o99', 'admission_offer_letter', 'Offer Letter Issued', 'Send digital offer letter', 'ADMISSION', 'offer_issued', 'On Offer Issued', 'HIGH', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Offer Letter Issued', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa0009hm1o1o436bzz', 'cmrvmxa4u0014hmmkreax8o99', 'admission_enrollment_complete', 'Enrollment Complete', 'Welcome after enrollment', 'ADMISSION', 'enrollment_complete', 'On Enrollment Complete', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Enrollment Complete', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa000ahm1o8fyb7rd0', 'cmrvmxa4u0014hmmkreax8o99', 'fee_due_reminder', 'Fee Due Reminder', 'Remind before fee due date', 'FEES', 'fee_due_soon', '3 Days Before Due Date', 'HIGH', 'SCHEDULED', true, true, true, true, true, true, false, 'Fee Due Reminder', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoa000bhm1ot5n558l0', 'cmrvmxa4u0014hmmkreax8o99', 'fee_overdue', 'Fee Overdue Alert', 'Alert after due date passes', 'FEES', 'fee_overdue', 'On Fee Overdue', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, false, 'Fee Overdue Alert', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000chm1ojtofiwj9', 'cmrvmxa4u0014hmmkreax8o99', 'fee_payment_success', 'Payment Success', 'Confirm successful payment', 'FEES', 'payment_success', 'On Payment Success', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Payment Success', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000dhm1ork5w95ky', 'cmrvmxa4u0014hmmkreax8o99', 'fee_payment_failed', 'Payment Failed', 'Notify failed online payment', 'FEES', 'payment_failed', 'On Payment Failed', 'HIGH', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Payment Failed', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000ehm1ov6vj0fde', 'cmrvmxa4u0014hmmkreax8o99', 'fee_receipt_generated', 'Receipt Generated', 'Share fee receipt link', 'FEES', 'receipt_generated', 'On Receipt Generated', 'MEDIUM', 'IMMEDIATELY', true, true, false, false, true, true, false, 'Receipt Generated', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000fhm1om2g30eii', 'cmrvmxa4u0014hmmkreax8o99', 'fee_concession_approved', 'Concession Approved', 'Notify concession approval', 'FEES', 'concession_approved', 'On Concession Approved', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, true, 'Concession Approved', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000ghm1oc3mroip7', 'cmrvmxa4u0014hmmkreax8o99', 'fee_installment_due', 'Installment Due', 'Upcoming installment reminder', 'FEES', 'installment_due', '2 Days Before Installment', 'MEDIUM', 'SCHEDULED', true, true, true, false, true, true, false, 'Installment Due', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000hhm1o8duce1km', 'cmrvmxa4u0014hmmkreax8o99', 'fee_partial_payment', 'Partial Payment Received', 'Acknowledge partial payment', 'FEES', 'partial_payment', 'On Partial Payment', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Partial Payment Received', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000ihm1oldeylwxq', 'cmrvmxa4u0014hmmkreax8o99', 'fee_defaulter_list', 'Defaulter List Alert', 'Daily defaulter digest for staff', 'FEES', 'defaulter_digest', 'Daily at 9 AM', 'MEDIUM', 'SCHEDULED', true, true, true, false, false, false, true, 'Defaulter List Alert', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000jhm1o13hx732a', 'cmrvmxa4u0014hmmkreax8o99', 'fee_refund_processed', 'Refund Processed', 'Confirm refund completion', 'FEES', 'refund_processed', 'On Refund Processed', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Refund Processed', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000khm1oulwnabls', 'cmrvmxa4u0014hmmkreax8o99', 'timetable_updated', 'Timetable Updated', 'Notify timetable changes', 'ACADEMICS', 'timetable_updated', 'On Timetable Update', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Timetable Updated', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000lhm1othb987ht', 'cmrvmxa4u0014hmmkreax8o99', 'homework_assigned', 'Homework Assigned', 'New homework notification', 'ACADEMICS', 'homework_assigned', 'On Homework Assigned', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Homework Assigned', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000mhm1oaghl9vba', 'cmrvmxa4u0014hmmkreax8o99', 'homework_due', 'Homework Due Reminder', 'Remind before homework due', 'ACADEMICS', 'homework_due', '1 Day Before Due', 'MEDIUM', 'SCHEDULED', true, true, true, false, true, true, false, 'Homework Due Reminder', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000nhm1or2wytxa6', 'cmrvmxa4u0014hmmkreax8o99', 'class_cancelled', 'Class Cancelled', 'Notify cancelled class', 'ACADEMICS', 'class_cancelled', 'On Class Cancelled', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, false, 'Class Cancelled', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000ohm1o96ui5neu', 'cmrvmxa4u0014hmmkreax8o99', 'substitution_assigned', 'Substitution Assigned', 'Staff substitution alert', 'ACADEMICS', 'substitution', 'On Substitution Assigned', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Substitution Assigned', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000phm1oyvv3xbq7', 'cmrvmxa4u0014hmmkreax8o99', 'syllabus_published', 'Syllabus Published', 'New syllabus available', 'ACADEMICS', 'syllabus_published', 'On Syllabus Publish', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Syllabus Published', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000qhm1o6mb767s2', 'cmrvmxa4u0014hmmkreax8o99', 'live_class_starting', 'Live Class Starting', 'Join reminder for live class', 'ACADEMICS', 'live_class_soon', '15 Min Before Start', 'MEDIUM', 'SCHEDULED', true, true, true, false, true, true, false, 'Live Class Starting', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000rhm1ocogun82o', 'cmrvmxa4u0014hmmkreax8o99', 'assignment_graded', 'Assignment Graded', 'Notify when marks are published', 'ACADEMICS', 'assignment_graded', 'On Assignment Graded', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Assignment Graded', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000shm1o7a091wa4', 'cmrvmxa4u0014hmmkreax8o99', 'academic_calendar_update', 'Calendar Update', 'Academic calendar change', 'ACADEMICS', 'calendar_updated', 'On Calendar Update', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Calendar Update', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000thm1oi36vydr4', 'cmrvmxa4u0014hmmkreax8o99', 'exam_schedule_published', 'Exam Schedule Published', 'Share exam timetable', 'EXAMINATIONS', 'exam_schedule', 'On Schedule Published', 'HIGH', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Exam Schedule Published', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000uhm1o0worcdrh', 'cmrvmxa4u0014hmmkreax8o99', 'admit_card_ready', 'Admit Card Ready', 'Admit card download link', 'EXAMINATIONS', 'admit_card_ready', 'On Admit Card Ready', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Admit Card Ready', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000vhm1o4rdgiln1', 'cmrvmxa4u0014hmmkreax8o99', 'exam_reminder', 'Exam Reminder', 'Day-before exam reminder', 'EXAMINATIONS', 'exam_tomorrow', '1 Day Before Exam', 'MEDIUM', 'SCHEDULED', true, true, true, false, true, true, false, 'Exam Reminder', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000whm1ongj0ask9', 'cmrvmxa4u0014hmmkreax8o99', 'result_published', 'Result Published', 'Notify when results go live', 'EXAMINATIONS', 'result_published', 'On Result Published', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, false, 'Result Published', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000xhm1o7x0db99m', 'cmrvmxa4u0014hmmkreax8o99', 'revaluation_update', 'Revaluation Update', 'Revaluation status change', 'EXAMINATIONS', 'revaluation_update', 'On Revaluation Update', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Revaluation Update', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aob000yhm1ogjlga8bi', 'cmrvmxa4u0014hmmkreax8o99', 'marksheet_available', 'Marksheet Available', 'Digital marksheet ready', 'EXAMINATIONS', 'marksheet_ready', 'On Marksheet Ready', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Marksheet Available', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc000zhm1oiwlbur15', 'cmrvmxa4u0014hmmkreax8o99', 'exam_hall_ticket', 'Hall Ticket Issued', 'Hall ticket notification', 'EXAMINATIONS', 'hall_ticket', 'On Hall Ticket Issued', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Hall Ticket Issued', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0010hm1o0px0u8fx', 'cmrvmxa4u0014hmmkreax8o99', 'exam_cancelled', 'Exam Cancelled', 'Urgent exam cancellation', 'EXAMINATIONS', 'exam_cancelled', 'On Exam Cancelled', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, false, 'Exam Cancelled', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0011hm1o0xhfwt0a', 'cmrvmxa4u0014hmmkreax8o99', 'student_absent', 'Student Absent Alert', 'Notify parents on absence', 'ATTENDANCE', 'student_absent', 'On Marked Absent', 'HIGH', 'IMMEDIATELY', true, true, true, true, false, true, false, 'Student Absent Alert', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0012hm1ouiby5u3n', 'cmrvmxa4u0014hmmkreax8o99', 'late_arrival', 'Late Arrival', 'Notify late check-in', 'ATTENDANCE', 'late_arrival', 'On Late Arrival', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Late Arrival', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0013hm1ougtgs8ky', 'cmrvmxa4u0014hmmkreax8o99', 'attendance_summary', 'Weekly Attendance Summary', 'Weekly attendance digest', 'ATTENDANCE', 'attendance_weekly', 'Every Monday 8 AM', 'MEDIUM', 'SCHEDULED', true, true, true, false, true, true, false, 'Weekly Attendance Summary', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0014hm1oeje122mu', 'cmrvmxa4u0014hmmkreax8o99', 'low_attendance_warning', 'Low Attendance Warning', 'Alert when attendance drops', 'ATTENDANCE', 'low_attendance', 'Below 75% Threshold', 'HIGH', 'IMMEDIATELY', true, true, true, false, true, true, false, 'Low Attendance Warning', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0015hm1od4007yz5', 'cmrvmxa4u0014hmmkreax8o99', 'staff_absent', 'Staff Absent Alert', 'Notify HR of staff absence', 'ATTENDANCE', 'staff_absent', 'On Staff Absent', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Staff Absent Alert', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0016hm1owiyl5gaf', 'cmrvmxa4u0014hmmkreax8o99', 'leave_approved', 'Leave Approved', 'Staff leave approval notice', 'HR', 'leave_approved', 'On Leave Approved', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Leave Approved', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0017hm1ouyrdhrih', 'cmrvmxa4u0014hmmkreax8o99', 'leave_rejected', 'Leave Rejected', 'Staff leave rejection notice', 'HR', 'leave_rejected', 'On Leave Rejected', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Leave Rejected', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0018hm1oj70k9q5i', 'cmrvmxa4u0014hmmkreax8o99', 'payroll_processed', 'Payroll Processed', 'Salary processed confirmation', 'HR', 'payroll_processed', 'On Payroll Processed', 'HIGH', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Payroll Processed', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc0019hm1o0xqt6fuy', 'cmrvmxa4u0014hmmkreax8o99', 'staff_announcement', 'Staff Announcement', 'Broadcast HR announcements', 'HR', 'staff_announcement', 'On Announcement Publish', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, false, false, true, 'Staff Announcement', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001ahm1o5z5pjz7t', 'cmrvmxa4u0014hmmkreax8o99', 'appraisal_reminder', 'Appraisal Reminder', 'Upcoming appraisal cycle', 'HR', 'appraisal_reminder', '7 Days Before Cycle', 'MEDIUM', 'SCHEDULED', true, true, true, false, false, false, true, 'Appraisal Reminder', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001bhm1ob8js9nat', 'cmrvmxa4u0014hmmkreax8o99', 'school_announcement', 'School Announcement', 'General campus announcements', 'GENERAL', 'announcement', 'On Announcement Publish', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, true, 'School Announcement', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001chm1o00bmir8x', 'cmrvmxa4u0014hmmkreax8o99', 'holiday_notice', 'Holiday Notice', 'Notify declared holidays', 'GENERAL', 'holiday_declared', 'On Holiday Declared', 'MEDIUM', 'IMMEDIATELY', true, true, true, false, true, true, true, 'Holiday Notice', 'Hello {{name}},
INSERT INTO public.notification_triggers (id, tenant_id, key, name, description, module, event_key, event_label, priority, send_timing, channel_whatsapp, channel_email, channel_push, channel_sms, recipient_student, recipient_parent, recipient_staff, message_subject, message_body, is_active, is_scheduled_today, week_sent_count, sort_order, created_at, updated_at) VALUES ('cmsmu9aoc001dhm1ow4izxzh8', 'cmrvmxa4u0014hmmkreax8o99', 'emergency_alert', 'Emergency Alert', 'Critical campus emergency', 'GENERAL', 'emergency', 'On Emergency Raised', 'HIGH', 'IMMEDIATELY', true, true, true, true, true, true, true, 'Emergency Alert', 'Hello {{name}},
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ehm1owql5q8gk', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001fhm1oxbu5m0bq', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ghm1oqd0d5jce', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001hhm1odecm8t8v', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ihm1oa651egkv', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aob000shm1o7a091wa4', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001jhm1oct9vofz0', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001khm1oqgak05k0', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001lhm1o56m4u18i', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001mhm1oedhto8x9', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'sms', 13, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001nhm1oxdvos4nm', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001ohm1o8utus46d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0002hm1o2rrj5bsi', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001phm1owc5h7qsd', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001qhm1o6b8ancg8', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001rhm1ow2tqlfmz', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001shm1orzyzn53d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001thm1o4ff5j567', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0004hm1obmo31zra', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001uhm1oav9dy94b', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001vhm1oruc19r4d', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001whm1okhxd8dkw', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001xhm1ohtdgwtny', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001yhm1oq0t0oype', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0009hm1o1o436bzz', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon001zhm1odlfp4zzx', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0020hm1o4zclcwtl', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0021hm1o5mnfiukn', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0022hm1o4566rbi2', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'sms', 13, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0023hm1o9f7hdjrm', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0024hm1o2bhh5u8i', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0005hm1owit8qzd5', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0025hm1oi9fp9pxm', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0026hm1o4ebwmito', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0027hm1onv9u2kif', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0028hm1oz42awkid', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon0029hm1opdpkq31v', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0006hm1o8pkdu083', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ahm1o0hqq7gdb', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002bhm1ofn8tnj28', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002chm1offt4y85g', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002dhm1osyji8w2h', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ehm1o8fvamkhd', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0008hm1ogo12094l', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002fhm1o5ov4866u', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ghm1omalkhmmf', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002hhm1o2vqb0zlg', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002ihm1oj5nnlhu7', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002jhm1oa632nkzy', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0003hm1osoe9qs0m', 'email', 30, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002khm1o2fpjn7sa', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'whatsapp', 48, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002lhm1o6nrb5mig', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'email', 33, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002mhm1o5swrl5ox', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'push', 22, 'DELIVERED', NULL, '2026-08-10 03:45:00') ON CONFLICT DO NOTHING;
INSERT INTO public.notification_trigger_logs (id, tenant_id, trigger_id, channel, recipient_count, status, error_message, created_at) VALUES ('cmsmu9aon002nhm1orxwf25tf', 'cmrvmxa4u0014hmmkreax8o99', 'cmsmu9aoa0007hm1oiriq3x54', 'whatsapp', 33, 'DELIVERED', NULL, '2026-08-09 19:30:00') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx901000ghmmk2v5ga1w6', 'sessions.view', 'View academic sessions') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zk0000hmmkteq0gjsz', 'tenants.manage', 'Create and administer tenants') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmrvmx8zy0006hmmk2aer223s', 'documents.manage', 'Design certificate, ID card, and exam templates') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cms6zjodu000lhmt0jb793itk', 'notifications.manage', 'Send campus notifications and announcements') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmsr6vjhu000whmkkqj85j3b3', 'live_classes.view', 'View LMS live class sessions') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmsrfswge000hhmrslus4v06f', 'academic_calendar.manage', 'Create and manage LMS academic calendar events') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb1000khmzkxf5g2h6t', 'library.manage', 'Manage library books and issue/return') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmsim4eq50000hmjkjhevijq1', 'transport.view', 'View transport routes and assignments') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions (id, key, description) VALUES ('cmspv3tb4000ohmzktb3alda3', 'online_exam.manage', 'Manage online exams, questions, attempts, and grading') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0002hm4cf2rs69da', 'cmrvmxa4u0014hmmkreax8o99', 'all_students', 'All Students', 'Broadcast to every student device', 0, true, 1, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0003hm4cgz1uhqnb', 'cmrvmxa4u0014hmmkreax8o99', 'all_parents', 'All Parents', 'Broadcast to every parent/guardian device', 0, true, 2, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0004hm4c7ef10qwv', 'cmrvmxa4u0014hmmkreax8o99', 'teachers', 'Teachers', 'Staff and teacher devices', 0, true, 3, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0005hm4cxvqir8vr', 'cmrvmxa4u0014hmmkreax8o99', 'examination', 'Examination', 'Exam schedules and result alerts', 0, true, 4, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.push_topics (id, tenant_id, key, name, description, subscriber_count, is_active, sort_order, created_at, updated_at) VALUES ('cmsmu3lsv0006hm4c8r4lxcrz', 'cmrvmxa4u0014hmmkreax8o99', 'fee_reminder', 'Fee Reminder', 'Fee due and payment confirmations', 0, true, 5, '2026-08-10 06:12:08.096', '2026-08-10 06:12:08.096') ON CONFLICT DO NOTHING;
INSERT INTO public.tenant_question_bank_settings (id, tenant_id, scope, enabled_question_types, show_question_marks, enabled_difficulties, auto_question_code, default_marks, negative_marking_enabled, negative_marks, negative_apply_to, prevent_duplicates, shuffle_questions, shuffle_options, allow_import, allow_export, require_approval, created_at, updated_at) VALUES ('cmskb868e0001hmo8cmhfu3og', 'cmrvmxa4u0014hmmkreax8o99', 'GLOBAL', '{MCQ_SINGLE,MCQ_MULTI,TRUE_FALSE,SHORT_ANSWER,LONG_ANSWER,FILL_BLANKS}', true, '{EASY,MEDIUM,HARD}', true, '{"MATCHING": 1, "MCQ_MULTI": 1, "MCQ_SINGLE": 1, "TRUE_FALSE": 1, "FILL_BLANKS": 1, "LONG_ANSWER": 5, "SHORT_ANSWER": 2}', true, 0.25, 'ALL', true, true, true, true, true, false, '2026-08-08 11:48:16.142', '2026-08-08 11:48:16.142') ON CONFLICT DO NOTHING;
INSERT INTO public.tenant_question_bank_settings (id, tenant_id, scope, enabled_question_types, show_question_marks, enabled_difficulties, auto_question_code, default_marks, negative_marking_enabled, negative_marks, negative_apply_to, prevent_duplicates, shuffle_questions, shuffle_options, allow_import, allow_export, require_approval, created_at, updated_at) VALUES ('cmsr1za85001hhmew36lb4vw3', 'cmspvcx300018hmzk7qyhss52', 'GLOBAL', '{MCQ_SINGLE,MCQ_MULTI,TRUE_FALSE,SHORT_ANSWER,LONG_ANSWER,FILL_BLANKS}', true, '{EASY,MEDIUM,HARD}', true, '{"MATCHING": 1, "MCQ_MULTI": 1, "MCQ_SINGLE": 1, "TRUE_FALSE": 1, "FILL_BLANKS": 1, "LONG_ANSWER": 5, "SHORT_ANSWER": 2}', true, 0.25, 'ALL', true, true, true, true, true, false, '2026-08-13 05:03:48.101', '2026-08-13 05:03:48.101') ON CONFLICT DO NOTHING;
INSERT INTO public.question_bank_difficulty_rules (id, tenant_id, setting_id, level, from_percent, to_percent, description, sort_order, created_at, updated_at) VALUES ('cmskb868e0002hmo8avuo1oog', 'cmrvmxa4u0014hmmkreax8o99', 'cmskb868e0001hmo8cmhfu3og', 'EASY', 71, 100, 'Most students answer correctly', 1, '2026-08-08 11:48:16.142', '2026-08-08 11:48:16.142') ON CONFLICT DO NOTHING;
SET session_replication_role = DEFAULT;
SET session_replication_role = DEFAULT;