SET session_replication_role = replica;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q30002hmr0q2p8z4bv', 'cmrvmxa4u0014hmmkreax8o99', 'welcome_new_student', 'Welcome - New Student', 'Sent when a student is enrolled', 'MESSAGE', 'Admission', 'en', NULL, 'Dear {{Parent Name}},

Welcome to {{School Name}}! {{Student Name}} (Adm No: {{Adm No}}) has been enrolled in {{Class}}-{{Section}}.

Regards,
{{School Name}}', true, true, true, true, true, true, 1, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q30003hmr0m2hlm75h', 'cmrvmxa4u0014hmmkreax8o99', 'fee_payment_reminder', 'Fee Payment Reminder', 'Reminder before fee due date', 'MESSAGE', 'Fees', 'en', NULL, 'Dear {{Parent Name}},

Fee of {{Amount}} for {{Student Name}} ({{Class}}-{{Section}}) is due on {{Due Date}}. Please pay on time.

â€” {{School Name}}', true, true, true, false, true, true, 2, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q30004hmr0zb2sx0kk', 'cmrvmxa4u0014hmmkreax8o99', 'fee_overdue_alert', 'Fee Overdue Alert', 'Alert after due date', 'MESSAGE', 'Fees', 'en', NULL, 'Dear {{Parent Name}}, fee of {{Amount}} for {{Student Name}} is overdue. Please clear dues at the earliest. â€” {{School Name}}', true, true, true, false, true, true, 3, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q30005hmr0p0r77the', 'cmrvmxa4u0014hmmkreax8o99', 'payment_success', 'Payment Success', 'Confirm successful payment', 'MESSAGE', 'Fees', 'en', NULL, 'Payment of {{Amount}} received for {{Student Name}}. Thank you. â€” {{School Name}}', true, true, true, false, true, true, 4, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q40006hmr0c0zf307p', 'cmrvmxa4u0014hmmkreax8o99', 'admission_approved', 'Admission Approved', 'Notify admission approval', 'MESSAGE', 'Admission', 'en', NULL, 'Congratulations! Admission of {{Student Name}} to {{Class}} at {{School Name}} is approved. Adm No: {{Adm No}}.', true, true, true, false, true, true, 5, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q40007hmr02t568yc9', 'cmrvmxa4u0014hmmkreax8o99', 'admission_document_request', 'Document Request', 'Request pending documents', 'MESSAGE', 'Admission', 'en', NULL, 'Dear {{Parent Name}}, please submit pending documents for {{Student Name}} at the earliest. â€” {{School Name}}', true, true, true, false, true, true, 6, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q40008hmr0cbscmq3d', 'cmrvmxa4u0014hmmkreax8o99', 'homework_assigned', 'Homework Assigned', 'New homework alert', 'MESSAGE', 'Academics', 'en', NULL, 'New homework assigned for {{Student Name}} ({{Class}}-{{Section}}). Due: {{Due Date}}.', true, false, true, false, true, true, 7, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q40009hmr0s0lcgzqu', 'cmrvmxa4u0014hmmkreax8o99', 'homework_due_reminder', 'Homework Due Reminder', 'Day-before homework reminder', 'MESSAGE', 'Academics', 'en', NULL, 'Reminder: homework for {{Student Name}} is due tomorrow ({{Due Date}}).', true, false, true, false, true, true, 8, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000ahmr0217h6g1p', 'cmrvmxa4u0014hmmkreax8o99', 'class_cancelled', 'Class Cancelled', 'Urgent cancellation notice', 'MESSAGE', 'Academics', 'en', NULL, 'Class for {{Class}}-{{Section}} on {{Date}} at {{Time}} has been cancelled. â€” {{School Name}}', true, true, true, false, true, true, 9, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000bhmr0l0k7v3hk', 'cmrvmxa4u0014hmmkreax8o99', 'live_class_starting', 'Live Class Starting', 'Join reminder for live class', 'MESSAGE', 'Academics', 'en', NULL, 'Live class for {{Class}}-{{Section}} starts at {{Time}}. Please join on time.', true, false, true, false, true, true, 10, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000chmr0q2j62suu', 'cmrvmxa4u0014hmmkreax8o99', 'exam_schedule_alert', 'Exam Schedule Alert', 'Exam timetable published', 'MESSAGE', 'Examinations', 'en', NULL, '{{Exam Name}} schedule is published for {{Student Name}}. Check the portal for details.', true, true, true, false, true, true, 11, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000dhmr0jkw7rys5', 'cmrvmxa4u0014hmmkreax8o99', 'exam_reminder', 'Exam Reminder', 'Day-before exam reminder', 'MESSAGE', 'Examinations', 'en', NULL, 'Reminder: {{Exam Name}} for {{Student Name}} is tomorrow ({{Date}}).', true, true, true, false, true, true, 12, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000ehmr01x8wb8xj', 'cmrvmxa4u0014hmmkreax8o99', 'result_published_msg', 'Result Published', 'Results available alert', 'MESSAGE', 'Examinations', 'en', NULL, 'Results for {{Exam Name}} are now available for {{Student Name}}. â€” {{School Name}}', true, true, true, false, true, true, 13, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000fhmr0kwh9o7ik', 'cmrvmxa4u0014hmmkreax8o99', 'admit_card_ready_msg', 'Admit Card Ready', 'Admit card download alert', 'MESSAGE', 'Examinations', 'en', NULL, 'Admit card for {{Exam Name}} is ready for {{Student Name}}. Download from the parent portal.', true, true, true, false, true, true, 14, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000ghmr05bsu5jwi', 'cmrvmxa4u0014hmmkreax8o99', 'student_absent_alert', 'Student Absent Alert', 'Notify parent on absence', 'MESSAGE', 'Attendance', 'en', NULL, 'Dear {{Parent Name}}, {{Student Name}} was marked absent on {{Date}}. â€” {{School Name}}', true, true, true, false, true, true, 15, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000hhmr0f3v7agr2', 'cmrvmxa4u0014hmmkreax8o99', 'late_arrival_alert', 'Late Arrival Alert', 'Late check-in notice', 'MESSAGE', 'Attendance', 'en', NULL, '{{Student Name}} arrived late on {{Date}} at {{Time}}. â€” {{School Name}}', true, false, true, false, true, true, 16, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000ihmr0p2ngbyh7', 'cmrvmxa4u0014hmmkreax8o99', 'low_attendance_warning', 'Low Attendance Warning', 'Attendance below threshold', 'MESSAGE', 'Attendance', 'en', NULL, 'Attendance for {{Student Name}} ({{Class}}-{{Section}}) is below the required threshold. Please contact school.', true, true, true, false, true, true, 17, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000jhmr0m8jnnw09', 'cmrvmxa4u0014hmmkreax8o99', 'holiday_notice_msg', 'Holiday Notice', 'Holiday declaration alert', 'MESSAGE', 'General', 'en', NULL, '{{School Name}} will remain closed on {{Date}}. Enjoy the holiday!', true, true, true, false, true, true, 18, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000khmr02fateet4', 'cmrvmxa4u0014hmmkreax8o99', 'school_announcement_msg', 'School Announcement', 'General announcement broadcast', 'MESSAGE', 'General', 'en', NULL, 'Announcement from {{School Name}}: please check the notice board / app for details.', true, true, true, false, true, true, 19, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q4000lhmr01k44w8r6', 'cmrvmxa4u0014hmmkreax8o99', 'transport_delay', 'Transport Delay', 'Bus delay notification', 'MESSAGE', 'Transport', 'en', NULL, 'School bus for {{Student Name}} is delayed. Expected time: {{Time}}. â€” {{School Name}}', true, true, true, false, true, true, 20, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000mhmr0zsl3x0mw', 'cmrvmxa4u0014hmmkreax8o99', 'library_due', 'Library Book Due', 'Book return reminder', 'MESSAGE', 'Library', 'en', NULL, 'Library book for {{Student Name}} is due on {{Due Date}}. Please return on time.', true, false, true, false, true, true, 21, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000nhmr0bxjsucd5', 'cmrvmxa4u0014hmmkreax8o99', 'id_card_ready', 'ID Card Ready', 'ID card collection notice', 'MESSAGE', 'General', 'en', NULL, 'ID card for {{Student Name}} ({{Adm No}}) is ready for collection. â€” {{School Name}}', true, true, true, false, true, true, 22, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000ohmr0ddtxzar8', 'cmrvmxa4u0014hmmkreax8o99', 'meeting_reminder', 'PTM Reminder', 'Parent-teacher meeting reminder', 'MESSAGE', 'General', 'en', NULL, 'PTM for {{Class}}-{{Section}} is scheduled on {{Date}} at {{Time}}. â€” {{School Name}}', true, true, true, false, true, true, 23, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000phmr0xznca2ui', 'cmrvmxa4u0014hmmkreax8o99', 'leave_approved_parent', 'Student Leave Approved', 'Leave approval to parent', 'MESSAGE', 'Attendance', 'en', NULL, 'Leave request for {{Student Name}} on {{Date}} has been approved.', true, false, true, false, true, true, 24, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000qhmr0fucovnoi', 'cmrvmxa4u0014hmmkreax8o99', 'fee_receipt_msg', 'Fee Receipt', 'Receipt available alert', 'MESSAGE', 'Fees', 'en', NULL, 'Fee receipt for {{Amount}} ({{Student Name}}) is available on the portal.', true, false, true, false, true, true, 25, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000rhmr0czha4vci', 'cmrvmxa4u0014hmmkreax8o99', 'installment_due_msg', 'Installment Due', 'Upcoming installment reminder', 'MESSAGE', 'Fees', 'en', NULL, 'Installment of {{Amount}} for {{Student Name}} is due on {{Due Date}}.', true, true, true, false, true, true, 26, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000shmr0rai7gstj', 'cmrvmxa4u0014hmmkreax8o99', 'assignment_graded_msg', 'Assignment Graded', 'Marks published alert', 'MESSAGE', 'Academics', 'en', NULL, 'Assignment for {{Student Name}} has been graded. Check the portal for scores.', true, false, true, false, true, true, 27, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000thmr02lsim9l5', 'cmrvmxa4u0014hmmkreax8o99', 'syllabus_update_msg', 'Syllabus Update', 'Syllabus change alert', 'MESSAGE', 'Academics', 'en', NULL, 'Syllabus for {{Class}}-{{Section}} has been updated. Please review on the app.', true, false, true, false, true, true, 28, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000uhmr09ggw7anm', 'cmrvmxa4u0014hmmkreax8o99', 'event_invite_msg', 'Event Invitation', 'School event invite', 'MESSAGE', 'General', 'en', NULL, 'You are invited to {{School Name}} event on {{Date}} at {{Time}}. â€” {{School Name}}', true, true, true, false, true, true, 29, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000vhmr0y5ngzgvy', 'cmrvmxa4u0014hmmkreax8o99', 'birthday_wish_msg', 'Birthday Wish', 'Student birthday greeting', 'MESSAGE', 'General', 'en', NULL, 'Happy Birthday {{Student Name}}! Wishing you a wonderful year ahead. â€” {{School Name}}', true, false, true, false, true, true, 30, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000whmr057fohhzt', 'cmrvmxa4u0014hmmkreax8o99', 'staff_leave_approved', 'Staff Leave Approved', 'Leave approval for staff', 'MESSAGE', 'HR', 'en', NULL, 'Dear {{Staff Name}}, your leave on {{Date}} has been approved. â€” {{School Name}}', true, false, true, false, true, true, 31, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000xhmr0whblb1ys', 'cmrvmxa4u0014hmmkreax8o99', 'payroll_processed_msg', 'Payroll Processed', 'Salary processed alert', 'MESSAGE', 'HR', 'en', NULL, 'Dear {{Staff Name}}, payroll for this month has been processed. â€” {{School Name}}', true, false, true, true, true, true, 32, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000yhmr0zz50jusz', 'cmrvmxa4u0014hmmkreax8o99', 'emergency_alert_msg', 'Emergency Alert', 'Critical emergency broadcast', 'MESSAGE', 'General', 'en', NULL, 'EMERGENCY from {{School Name}}: please check your phone / portal immediately.', true, true, true, false, true, true, 33, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q5000zhmr051op26af', 'cmrvmxa4u0014hmmkreax8o99', 'revaluation_update_msg', 'Revaluation Update', 'Revaluation status message', 'MESSAGE', 'Examinations', 'en', NULL, 'Revaluation update for {{Student Name}} ({{Exam Name}}) is available on the portal.', true, false, true, false, false, true, 34, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q50010hmr0i6bzjg3v', 'cmrvmxa4u0014hmmkreax8o99', 'waitlist_update_msg', 'Waitlist Update', 'Admission waitlist change', 'MESSAGE', 'Admission', 'en', NULL, 'Waitlist status for {{Student Name}} has been updated. Please check the portal.', true, true, true, false, false, false, 35, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q50011hmr0iigg1llg', 'cmrvmxa4u0014hmmkreax8o99', 'unused_promo_msg', 'Promotional Offer', 'Unused promotional template', 'MESSAGE', 'General', 'en', NULL, 'Special offer from {{School Name}} for {{Parent Name}}. Contact office for details.', true, true, true, false, false, false, 36, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60012hmr05qho12ig', 'cmrvmxa4u0014hmmkreax8o99', 'exam_timetable_notice', 'Exam Timetable Notice', 'Published exam timetable for portal', 'NOTICE', 'Examinations', 'en', 'Exam Timetable Notice', 'Dear Parents,

The timetable for {{Exam Name}} has been published.

Student: {{Student Name}}
Class: {{Class}}-{{Section}}

Please download the schedule from the parent portal.

â€” {{School Name}}', false, false, true, true, true, true, 37, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60013hmr0qjf7laex', 'cmrvmxa4u0014hmmkreax8o99', 'fee_structure_notice', 'Fee Structure Notice', 'Annual fee structure announcement', 'NOTICE', 'Fees', 'en', 'Fee Structure Notice', 'Fee structure for the academic year is now available. Please review dues for {{Student Name}} ({{Class}}-{{Section}}).', false, false, true, true, true, true, 38, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60014hmr0999brgl9', 'cmrvmxa4u0014hmmkreax8o99', 'academic_calendar_notice', 'Academic Calendar Notice', 'Calendar publication notice', 'NOTICE', 'Academics', 'en', 'Academic Calendar Notice', 'Academic calendar has been updated. Holidays and events are listed on the portal.', false, false, true, true, true, true, 39, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60015hmr0ucrvfu8z', 'cmrvmxa4u0014hmmkreax8o99', 'uniform_policy_notice', 'Uniform Policy Notice', 'Dress code reminder', 'NOTICE', 'General', 'en', 'Uniform Policy Notice', 'All students must follow the school uniform policy from {{Date}}. Contact office for queries.', false, false, true, true, true, true, 40, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60016hmr0n6o58eyc', 'cmrvmxa4u0014hmmkreax8o99', 'ptm_notice', 'Parent Teacher Meeting', 'PTM schedule notice', 'NOTICE', 'General', 'en', 'Parent Teacher Meeting', 'PTM for {{Class}}-{{Section}} will be held on {{Date}} at {{Time}}. Your presence is requested.', false, false, true, true, true, true, 41, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60017hmr0jim0n94u', 'cmrvmxa4u0014hmmkreax8o99', 'result_declaration_notice', 'Result Declaration', 'Result day notice', 'NOTICE', 'Examinations', 'en', 'Result Declaration', 'Results for {{Exam Name}} will be declared on {{Date}}. Parents may collect report cards from school.', false, false, true, true, true, true, 42, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60018hmr07ho3zpv8', 'cmrvmxa4u0014hmmkreax8o99', 'sports_day_notice', 'Sports Day Notice', 'Annual sports day invite', 'NOTICE', 'General', 'en', 'Sports Day Notice', 'Annual Sports Day will be celebrated on {{Date}}. Students of {{Class}} are requested to participate.', false, false, true, true, true, true, 43, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q60019hmr0xvtdh2lj', 'cmrvmxa4u0014hmmkreax8o99', 'library_rules_notice', 'Library Rules', 'Library usage guidelines', 'NOTICE', 'Library', 'en', 'Library Rules', 'Updated library rules are in effect from {{Date}}. Please ensure books are returned by {{Due Date}}.', false, false, true, true, true, true, 44, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001ahmr0wbmkcoh7', 'cmrvmxa4u0014hmmkreax8o99', 'transport_route_notice', 'Transport Route Change', 'Bus route update notice', 'NOTICE', 'Transport', 'en', 'Transport Route Change', 'Transport routes have been revised. Please check the updated stop timings on the portal.', false, false, true, true, true, true, 45, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001bhmr0m5icbbtq', 'cmrvmxa4u0014hmmkreax8o99', 'health_checkup_notice', 'Health Checkup Notice', 'Annual health checkup', 'NOTICE', 'General', 'en', 'Health Checkup Notice', 'Health checkup for students will be conducted on {{Date}}. Consent forms are available on the portal.', false, false, true, true, true, true, 46, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001chmr0ornpfzj9', 'cmrvmxa4u0014hmmkreax8o99', 'exam_hall_ticket_notice', 'Hall Ticket Notice', 'Hall ticket collection', 'NOTICE', 'Examinations', 'en', 'Hall Ticket Notice', 'Hall tickets for {{Exam Name}} are ready. Collect from office with Adm No {{Adm No}}.', false, false, true, true, true, true, 47, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001dhmr00dkrgj06', 'cmrvmxa4u0014hmmkreax8o99', 'attendance_policy_notice', 'Attendance Policy', 'Minimum attendance policy', 'NOTICE', 'Attendance', 'en', 'Attendance Policy', 'Students must maintain minimum attendance. Parents of {{Student Name}} will be notified if below threshold.', false, false, true, true, true, true, 48, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001ehmr08bzu3q13', 'cmrvmxa4u0014hmmkreax8o99', 'unused_draft_notice', 'Draft Circular', 'Unused draft circular', 'NOTICE', 'General', 'en', 'Draft Circular', 'Draft circular content for internal review only.', false, false, true, true, false, false, 49, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001fhmr07ulgyx32', 'cmrvmxa4u0014hmmkreax8o99', 'summer_camp_notice', 'Summer Camp Notice', 'Summer camp registration', 'NOTICE', 'General', 'en', 'Summer Camp Notice', 'Summer camp registration opens on {{Date}}. Limited seats for {{Class}} students.', false, false, true, true, true, true, 50, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001ghmr01xvkiaaw', 'cmrvmxa4u0014hmmkreax8o99', 'welcome_email', 'Welcome Email', 'Full welcome email for new admissions', 'EMAIL', 'Admission', 'en', 'Welcome Email', 'Dear {{Parent Name}},

We are delighted to welcome {{Student Name}} to {{School Name}}.

Class: {{Class}}-{{Section}}
Admission No: {{Adm No}}

Please complete the onboarding checklist on the portal.

Warm regards,
{{School Name}}', false, false, false, true, true, true, 51, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001hhmr0awyxp9nn', 'cmrvmxa4u0014hmmkreax8o99', 'fee_invoice_email', 'Fee Invoice Email', 'Detailed fee invoice email', 'EMAIL', 'Fees', 'en', 'Fee Invoice Email', 'Dear {{Parent Name}},

Please find the fee invoice for {{Student Name}}.
Amount Due: {{Amount}}
Due Date: {{Due Date}}

Pay online via the parent portal.

â€” Accounts, {{School Name}}', false, false, false, true, true, true, 52, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001ihmr006vi9jit', 'cmrvmxa4u0014hmmkreax8o99', 'report_card_email', 'Report Card Email', 'Report card delivery email', 'EMAIL', 'Examinations', 'en', 'Report Card Email', 'Dear {{Parent Name}},

The report card for {{Student Name}} ({{Exam Name}}) is attached / available on the portal.

â€” {{School Name}}', false, false, false, true, true, true, 53, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0022hm94uaq04rp9', 'cmspvcx300018hmzk7qyhss52', 'meeting_reminder', 'PTM Reminder', 'Parent-teacher meeting reminder', 'MESSAGE', 'General', 'en', NULL, 'PTM for {{Class}}-{{Section}} is scheduled on {{Date}} at {{Time}}. â€” {{School Name}}', true, true, true, false, true, true, 23, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001jhmr0di4r0uvk', 'cmrvmxa4u0014hmmkreax8o99', 'leave_status_email', 'Leave Status Email', 'Staff leave status email', 'EMAIL', 'HR', 'en', 'Leave Status Email', 'Dear {{Staff Name}},

Your leave request for {{Date}} has been updated. Please check HR portal for details.

â€” {{School Name}}', false, false, false, true, true, true, 54, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001khmr0l3qifflp', 'cmrvmxa4u0014hmmkreax8o99', 'newsletter_email', 'Monthly Newsletter', 'School newsletter email', 'EMAIL', 'General', 'en', 'Monthly Newsletter', 'Dear Parents,

Here is the monthly newsletter from {{School Name}}. Highlights for {{Class}} are available on the portal.

â€” {{School Name}}', false, false, false, true, true, true, 55, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001lhmr0057l8erv', 'cmrvmxa4u0014hmmkreax8o99', 'password_reset_email', 'Password Reset', 'Portal password reset email', 'EMAIL', 'System', 'en', 'Password Reset', 'Dear user,

A password reset was requested for your {{School Name}} account. If this wasn''t you, contact support.

â€” {{School Name}}', false, false, false, true, true, true, 56, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001mhmr0kz53wuni', 'cmrvmxa4u0014hmmkreax8o99', 'event_confirmation_email', 'Event Confirmation', 'Event registration confirmation', 'EMAIL', 'General', 'en', 'Event Confirmation', 'Dear {{Parent Name}},

Your registration for the school event on {{Date}} at {{Time}} is confirmed for {{Student Name}}.

â€” {{School Name}}', false, false, false, true, true, true, 57, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmsmuj9q6001nhmr0tax9nebu', 'cmrvmxa4u0014hmmkreax8o99', 'unused_alumni_email', 'Alumni Outreach', 'Unused alumni outreach email', 'EMAIL', 'General', 'en', 'Alumni Outreach', 'Dear Alumni,

We would love to reconnect. Visit {{School Name}} portal for updates.', false, false, false, true, true, false, 58, '2026-08-10 06:24:18.939', '2026-08-10 06:24:18.939') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddi001ghm94boz9tsc8', 'cmspvcx300018hmzk7qyhss52', 'welcome_new_student', 'Welcome - New Student', 'Sent when a student is enrolled', 'MESSAGE', 'Admission', 'en', NULL, 'Dear {{Parent Name}},

Welcome to {{School Name}}! {{Student Name}} (Adm No: {{Adm No}}) has been enrolled in {{Class}}-{{Section}}.

Regards,
{{School Name}}', true, true, true, true, true, true, 1, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddi001hhm94uocqc7ca', 'cmspvcx300018hmzk7qyhss52', 'fee_payment_reminder', 'Fee Payment Reminder', 'Reminder before fee due date', 'MESSAGE', 'Fees', 'en', NULL, 'Dear {{Parent Name}},

Fee of {{Amount}} for {{Student Name}} ({{Class}}-{{Section}}) is due on {{Due Date}}. Please pay on time.

â€” {{School Name}}', true, true, true, false, true, true, 2, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddi001ihm94sjzlxdht', 'cmspvcx300018hmzk7qyhss52', 'fee_overdue_alert', 'Fee Overdue Alert', 'Alert after due date', 'MESSAGE', 'Fees', 'en', NULL, 'Dear {{Parent Name}}, fee of {{Amount}} for {{Student Name}} is overdue. Please clear dues at the earliest. â€” {{School Name}}', true, true, true, false, true, true, 3, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddi001jhm941j0zlsax', 'cmspvcx300018hmzk7qyhss52', 'payment_success', 'Payment Success', 'Confirm successful payment', 'MESSAGE', 'Fees', 'en', NULL, 'Payment of {{Amount}} received for {{Student Name}}. Thank you. â€” {{School Name}}', true, true, true, false, true, true, 4, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddi001khm94edtw08od', 'cmspvcx300018hmzk7qyhss52', 'admission_approved', 'Admission Approved', 'Notify admission approval', 'MESSAGE', 'Admission', 'en', NULL, 'Congratulations! Admission of {{Student Name}} to {{Class}} at {{School Name}} is approved. Adm No: {{Adm No}}.', true, true, true, false, true, true, 5, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddi001lhm948f22exbf', 'cmspvcx300018hmzk7qyhss52', 'admission_document_request', 'Document Request', 'Request pending documents', 'MESSAGE', 'Admission', 'en', NULL, 'Dear {{Parent Name}}, please submit pending documents for {{Student Name}} at the earliest. â€” {{School Name}}', true, true, true, false, true, true, 6, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddi001mhm94o44t7tnn', 'cmspvcx300018hmzk7qyhss52', 'homework_assigned', 'Homework Assigned', 'New homework alert', 'MESSAGE', 'Academics', 'en', NULL, 'New homework assigned for {{Student Name}} ({{Class}}-{{Section}}). Due: {{Due Date}}.', true, false, true, false, true, true, 7, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001nhm943ofar49t', 'cmspvcx300018hmzk7qyhss52', 'homework_due_reminder', 'Homework Due Reminder', 'Day-before homework reminder', 'MESSAGE', 'Academics', 'en', NULL, 'Reminder: homework for {{Student Name}} is due tomorrow ({{Due Date}}).', true, false, true, false, true, true, 8, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001ohm94jv6n4rwb', 'cmspvcx300018hmzk7qyhss52', 'class_cancelled', 'Class Cancelled', 'Urgent cancellation notice', 'MESSAGE', 'Academics', 'en', NULL, 'Class for {{Class}}-{{Section}} on {{Date}} at {{Time}} has been cancelled. â€” {{School Name}}', true, true, true, false, true, true, 9, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001phm948hxr8uhm', 'cmspvcx300018hmzk7qyhss52', 'live_class_starting', 'Live Class Starting', 'Join reminder for live class', 'MESSAGE', 'Academics', 'en', NULL, 'Live class for {{Class}}-{{Section}} starts at {{Time}}. Please join on time.', true, false, true, false, true, true, 10, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001qhm94vr0bs3wq', 'cmspvcx300018hmzk7qyhss52', 'exam_schedule_alert', 'Exam Schedule Alert', 'Exam timetable published', 'MESSAGE', 'Examinations', 'en', NULL, '{{Exam Name}} schedule is published for {{Student Name}}. Check the portal for details.', true, true, true, false, true, true, 11, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001rhm94bbx91ouo', 'cmspvcx300018hmzk7qyhss52', 'exam_reminder', 'Exam Reminder', 'Day-before exam reminder', 'MESSAGE', 'Examinations', 'en', NULL, 'Reminder: {{Exam Name}} for {{Student Name}} is tomorrow ({{Date}}).', true, true, true, false, true, true, 12, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001shm94g4uro25m', 'cmspvcx300018hmzk7qyhss52', 'result_published_msg', 'Result Published', 'Results available alert', 'MESSAGE', 'Examinations', 'en', NULL, 'Results for {{Exam Name}} are now available for {{Student Name}}. â€” {{School Name}}', true, true, true, false, true, true, 13, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001thm9418gl8n8t', 'cmspvcx300018hmzk7qyhss52', 'admit_card_ready_msg', 'Admit Card Ready', 'Admit card download alert', 'MESSAGE', 'Examinations', 'en', NULL, 'Admit card for {{Exam Name}} is ready for {{Student Name}}. Download from the parent portal.', true, true, true, false, true, true, 14, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001uhm946nhgqrq8', 'cmspvcx300018hmzk7qyhss52', 'student_absent_alert', 'Student Absent Alert', 'Notify parent on absence', 'MESSAGE', 'Attendance', 'en', NULL, 'Dear {{Parent Name}}, {{Student Name}} was marked absent on {{Date}}. â€” {{School Name}}', true, true, true, false, true, true, 15, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001vhm94enm6fphj', 'cmspvcx300018hmzk7qyhss52', 'late_arrival_alert', 'Late Arrival Alert', 'Late check-in notice', 'MESSAGE', 'Attendance', 'en', NULL, '{{Student Name}} arrived late on {{Date}} at {{Time}}. â€” {{School Name}}', true, false, true, false, true, true, 16, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001whm945lxl9pej', 'cmspvcx300018hmzk7qyhss52', 'low_attendance_warning', 'Low Attendance Warning', 'Attendance below threshold', 'MESSAGE', 'Attendance', 'en', NULL, 'Attendance for {{Student Name}} ({{Class}}-{{Section}}) is below the required threshold. Please contact school.', true, true, true, false, true, true, 17, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001xhm94do26c0hk', 'cmspvcx300018hmzk7qyhss52', 'holiday_notice_msg', 'Holiday Notice', 'Holiday declaration alert', 'MESSAGE', 'General', 'en', NULL, '{{School Name}} will remain closed on {{Date}}. Enjoy the holiday!', true, true, true, false, true, true, 18, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001yhm94w8lxqmse', 'cmspvcx300018hmzk7qyhss52', 'school_announcement_msg', 'School Announcement', 'General announcement broadcast', 'MESSAGE', 'General', 'en', NULL, 'Announcement from {{School Name}}: please check the notice board / app for details.', true, true, true, false, true, true, 19, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj001zhm942q5n2m4n', 'cmspvcx300018hmzk7qyhss52', 'transport_delay', 'Transport Delay', 'Bus delay notification', 'MESSAGE', 'Transport', 'en', NULL, 'School bus for {{Student Name}} is delayed. Expected time: {{Time}}. â€” {{School Name}}', true, true, true, false, true, true, 20, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0020hm94ntvpsoo0', 'cmspvcx300018hmzk7qyhss52', 'library_due', 'Library Book Due', 'Book return reminder', 'MESSAGE', 'Library', 'en', NULL, 'Library book for {{Student Name}} is due on {{Due Date}}. Please return on time.', true, false, true, false, true, true, 21, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0021hm94i2bvkcne', 'cmspvcx300018hmzk7qyhss52', 'id_card_ready', 'ID Card Ready', 'ID card collection notice', 'MESSAGE', 'General', 'en', NULL, 'ID card for {{Student Name}} ({{Adm No}}) is ready for collection. â€” {{School Name}}', true, true, true, false, true, true, 22, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0023hm94usq80giz', 'cmspvcx300018hmzk7qyhss52', 'leave_approved_parent', 'Student Leave Approved', 'Leave approval to parent', 'MESSAGE', 'Attendance', 'en', NULL, 'Leave request for {{Student Name}} on {{Date}} has been approved.', true, false, true, false, true, true, 24, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0024hm949oi1h3v7', 'cmspvcx300018hmzk7qyhss52', 'fee_receipt_msg', 'Fee Receipt', 'Receipt available alert', 'MESSAGE', 'Fees', 'en', NULL, 'Fee receipt for {{Amount}} ({{Student Name}}) is available on the portal.', true, false, true, false, true, true, 25, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0025hm94pwx7bzcp', 'cmspvcx300018hmzk7qyhss52', 'installment_due_msg', 'Installment Due', 'Upcoming installment reminder', 'MESSAGE', 'Fees', 'en', NULL, 'Installment of {{Amount}} for {{Student Name}} is due on {{Due Date}}.', true, true, true, false, true, true, 26, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0026hm941nrxvj5h', 'cmspvcx300018hmzk7qyhss52', 'assignment_graded_msg', 'Assignment Graded', 'Marks published alert', 'MESSAGE', 'Academics', 'en', NULL, 'Assignment for {{Student Name}} has been graded. Check the portal for scores.', true, false, true, false, true, true, 27, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0027hm943asdtv97', 'cmspvcx300018hmzk7qyhss52', 'syllabus_update_msg', 'Syllabus Update', 'Syllabus change alert', 'MESSAGE', 'Academics', 'en', NULL, 'Syllabus for {{Class}}-{{Section}} has been updated. Please review on the app.', true, false, true, false, true, true, 28, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0028hm94ml3rfqod', 'cmspvcx300018hmzk7qyhss52', 'event_invite_msg', 'Event Invitation', 'School event invite', 'MESSAGE', 'General', 'en', NULL, 'You are invited to {{School Name}} event on {{Date}} at {{Time}}. â€” {{School Name}}', true, true, true, false, true, true, 29, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj0029hm94b0g1tgrz', 'cmspvcx300018hmzk7qyhss52', 'birthday_wish_msg', 'Birthday Wish', 'Student birthday greeting', 'MESSAGE', 'General', 'en', NULL, 'Happy Birthday {{Student Name}}! Wishing you a wonderful year ahead. â€” {{School Name}}', true, false, true, false, true, true, 30, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002ahm949hmucv38', 'cmspvcx300018hmzk7qyhss52', 'staff_leave_approved', 'Staff Leave Approved', 'Leave approval for staff', 'MESSAGE', 'HR', 'en', NULL, 'Dear {{Staff Name}}, your leave on {{Date}} has been approved. â€” {{School Name}}', true, false, true, false, true, true, 31, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002bhm94ivhcm3ce', 'cmspvcx300018hmzk7qyhss52', 'payroll_processed_msg', 'Payroll Processed', 'Salary processed alert', 'MESSAGE', 'HR', 'en', NULL, 'Dear {{Staff Name}}, payroll for this month has been processed. â€” {{School Name}}', true, false, true, true, true, true, 32, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002chm94lwgzjd23', 'cmspvcx300018hmzk7qyhss52', 'emergency_alert_msg', 'Emergency Alert', 'Critical emergency broadcast', 'MESSAGE', 'General', 'en', NULL, 'EMERGENCY from {{School Name}}: please check your phone / portal immediately.', true, true, true, false, true, true, 33, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002dhm94sxi4kcm8', 'cmspvcx300018hmzk7qyhss52', 'revaluation_update_msg', 'Revaluation Update', 'Revaluation status message', 'MESSAGE', 'Examinations', 'en', NULL, 'Revaluation update for {{Student Name}} ({{Exam Name}}) is available on the portal.', true, false, true, false, false, true, 34, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002ehm94g1oj6upk', 'cmspvcx300018hmzk7qyhss52', 'waitlist_update_msg', 'Waitlist Update', 'Admission waitlist change', 'MESSAGE', 'Admission', 'en', NULL, 'Waitlist status for {{Student Name}} has been updated. Please check the portal.', true, true, true, false, false, false, 35, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002fhm94kagcd77d', 'cmspvcx300018hmzk7qyhss52', 'unused_promo_msg', 'Promotional Offer', 'Unused promotional template', 'MESSAGE', 'General', 'en', NULL, 'Special offer from {{School Name}} for {{Parent Name}}. Contact office for details.', true, true, true, false, false, false, 36, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002ghm949ak7vswv', 'cmspvcx300018hmzk7qyhss52', 'exam_timetable_notice', 'Exam Timetable Notice', 'Published exam timetable for portal', 'NOTICE', 'Examinations', 'en', 'Exam Timetable Notice', 'Dear Parents,

The timetable for {{Exam Name}} has been published.

Student: {{Student Name}}
Class: {{Class}}-{{Section}}

Please download the schedule from the parent portal.

â€” {{School Name}}', false, false, true, true, true, true, 37, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddj002hhm94mk9q8yab', 'cmspvcx300018hmzk7qyhss52', 'fee_structure_notice', 'Fee Structure Notice', 'Annual fee structure announcement', 'NOTICE', 'Fees', 'en', 'Fee Structure Notice', 'Fee structure for the academic year is now available. Please review dues for {{Student Name}} ({{Class}}-{{Section}}).', false, false, true, true, true, true, 38, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002ihm94luduwtsk', 'cmspvcx300018hmzk7qyhss52', 'academic_calendar_notice', 'Academic Calendar Notice', 'Calendar publication notice', 'NOTICE', 'Academics', 'en', 'Academic Calendar Notice', 'Academic calendar has been updated. Holidays and events are listed on the portal.', false, false, true, true, true, true, 39, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002jhm946cgaqy8c', 'cmspvcx300018hmzk7qyhss52', 'uniform_policy_notice', 'Uniform Policy Notice', 'Dress code reminder', 'NOTICE', 'General', 'en', 'Uniform Policy Notice', 'All students must follow the school uniform policy from {{Date}}. Contact office for queries.', false, false, true, true, true, true, 40, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002khm94g4lx6hci', 'cmspvcx300018hmzk7qyhss52', 'ptm_notice', 'Parent Teacher Meeting', 'PTM schedule notice', 'NOTICE', 'General', 'en', 'Parent Teacher Meeting', 'PTM for {{Class}}-{{Section}} will be held on {{Date}} at {{Time}}. Your presence is requested.', false, false, true, true, true, true, 41, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002lhm94zlocwtdo', 'cmspvcx300018hmzk7qyhss52', 'result_declaration_notice', 'Result Declaration', 'Result day notice', 'NOTICE', 'Examinations', 'en', 'Result Declaration', 'Results for {{Exam Name}} will be declared on {{Date}}. Parents may collect report cards from school.', false, false, true, true, true, true, 42, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002mhm9462d5wimf', 'cmspvcx300018hmzk7qyhss52', 'sports_day_notice', 'Sports Day Notice', 'Annual sports day invite', 'NOTICE', 'General', 'en', 'Sports Day Notice', 'Annual Sports Day will be celebrated on {{Date}}. Students of {{Class}} are requested to participate.', false, false, true, true, true, true, 43, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002nhm94s3kwchm9', 'cmspvcx300018hmzk7qyhss52', 'library_rules_notice', 'Library Rules', 'Library usage guidelines', 'NOTICE', 'Library', 'en', 'Library Rules', 'Updated library rules are in effect from {{Date}}. Please ensure books are returned by {{Due Date}}.', false, false, true, true, true, true, 44, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002ohm94rz39163r', 'cmspvcx300018hmzk7qyhss52', 'transport_route_notice', 'Transport Route Change', 'Bus route update notice', 'NOTICE', 'Transport', 'en', 'Transport Route Change', 'Transport routes have been revised. Please check the updated stop timings on the portal.', false, false, true, true, true, true, 45, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002phm94k82nvqjv', 'cmspvcx300018hmzk7qyhss52', 'health_checkup_notice', 'Health Checkup Notice', 'Annual health checkup', 'NOTICE', 'General', 'en', 'Health Checkup Notice', 'Health checkup for students will be conducted on {{Date}}. Consent forms are available on the portal.', false, false, true, true, true, true, 46, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002qhm94aknrqulc', 'cmspvcx300018hmzk7qyhss52', 'exam_hall_ticket_notice', 'Hall Ticket Notice', 'Hall ticket collection', 'NOTICE', 'Examinations', 'en', 'Hall Ticket Notice', 'Hall tickets for {{Exam Name}} are ready. Collect from office with Adm No {{Adm No}}.', false, false, true, true, true, true, 47, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002rhm94xa0vg65n', 'cmspvcx300018hmzk7qyhss52', 'attendance_policy_notice', 'Attendance Policy', 'Minimum attendance policy', 'NOTICE', 'Attendance', 'en', 'Attendance Policy', 'Students must maintain minimum attendance. Parents of {{Student Name}} will be notified if below threshold.', false, false, true, true, true, true, 48, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002shm94x5nlrei1', 'cmspvcx300018hmzk7qyhss52', 'unused_draft_notice', 'Draft Circular', 'Unused draft circular', 'NOTICE', 'General', 'en', 'Draft Circular', 'Draft circular content for internal review only.', false, false, true, true, false, false, 49, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002thm944wnopcl2', 'cmspvcx300018hmzk7qyhss52', 'summer_camp_notice', 'Summer Camp Notice', 'Summer camp registration', 'NOTICE', 'General', 'en', 'Summer Camp Notice', 'Summer camp registration opens on {{Date}}. Limited seats for {{Class}} students.', false, false, true, true, true, true, 50, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002uhm94d0y5zm5q', 'cmspvcx300018hmzk7qyhss52', 'welcome_email', 'Welcome Email', 'Full welcome email for new admissions', 'EMAIL', 'Admission', 'en', 'Welcome Email', 'Dear {{Parent Name}},

We are delighted to welcome {{Student Name}} to {{School Name}}.

Class: {{Class}}-{{Section}}
Admission No: {{Adm No}}

Please complete the onboarding checklist on the portal.

Warm regards,
{{School Name}}', false, false, false, true, true, true, 51, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002vhm94am4pm6fh', 'cmspvcx300018hmzk7qyhss52', 'fee_invoice_email', 'Fee Invoice Email', 'Detailed fee invoice email', 'EMAIL', 'Fees', 'en', 'Fee Invoice Email', 'Dear {{Parent Name}},

Please find the fee invoice for {{Student Name}}.
Amount Due: {{Amount}}
Due Date: {{Due Date}}

Pay online via the parent portal.

â€” Accounts, {{School Name}}', false, false, false, true, true, true, 52, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002whm94nkhkawb1', 'cmspvcx300018hmzk7qyhss52', 'report_card_email', 'Report Card Email', 'Report card delivery email', 'EMAIL', 'Examinations', 'en', 'Report Card Email', 'Dear {{Parent Name}},

The report card for {{Student Name}} ({{Exam Name}}) is attached / available on the portal.

â€” {{School Name}}', false, false, false, true, true, true, 53, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002xhm94duvmwp02', 'cmspvcx300018hmzk7qyhss52', 'leave_status_email', 'Leave Status Email', 'Staff leave status email', 'EMAIL', 'HR', 'en', 'Leave Status Email', 'Dear {{Staff Name}},

Your leave request for {{Date}} has been updated. Please check HR portal for details.

â€” {{School Name}}', false, false, false, true, true, true, 54, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002yhm94roz9i0tt', 'cmspvcx300018hmzk7qyhss52', 'newsletter_email', 'Monthly Newsletter', 'School newsletter email', 'EMAIL', 'General', 'en', 'Monthly Newsletter', 'Dear Parents,

Here is the monthly newsletter from {{School Name}}. Highlights for {{Class}} are available on the portal.

â€” {{School Name}}', false, false, false, true, true, true, 55, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk002zhm94yow93lxu', 'cmspvcx300018hmzk7qyhss52', 'password_reset_email', 'Password Reset', 'Portal password reset email', 'EMAIL', 'System', 'en', 'Password Reset', 'Dear user,

A password reset was requested for your {{School Name}} account. If this wasn''t you, contact support.

â€” {{School Name}}', false, false, false, true, true, true, 56, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk0030hm94pv771rmo', 'cmspvcx300018hmzk7qyhss52', 'event_confirmation_email', 'Event Confirmation', 'Event registration confirmation', 'EMAIL', 'General', 'en', 'Event Confirmation', 'Dear {{Parent Name}},

Your registration for the school event on {{Date}} at {{Time}} is confirmed for {{Student Name}}.

â€” {{School Name}}', false, false, false, true, true, true, 57, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
INSERT INTO public.message_notice_templates (id, tenant_id, key, name, description, type, category, language, subject, body, channel_whatsapp, channel_sms, channel_push, channel_email, is_active, used_in_triggers, sort_order, created_at, updated_at) VALUES ('cmspzaddk0031hm94ljomoqoj', 'cmspvcx300018hmzk7qyhss52', 'unused_alumni_email', 'Alumni Outreach', 'Unused alumni outreach email', 'EMAIL', 'General', 'en', 'Alumni Outreach', 'Dear Alumni,

We would love to reconnect. Visit {{School Name}} portal for updates.', false, false, false, true, true, false, 58, '2026-08-12 11:00:40.373', '2026-08-12 11:00:40.373') ON CONFLICT DO NOTHING;
SET session_replication_role = DEFAULT;
